import { EventClientError, eventClientInstant, eventClientObject, eventClientUuid, parseEventReceipt, type EventBrowserOptions, type EventUploadGrant } from "./client";
import { EVENT_KIOSK_LIMITS, parseKioskApproval, parseKioskSession, parseKioskUnlock, type EventKioskApproval, type EventKioskSession } from "./kiosk-contract";
import { validateEventLook, type EventGuestContext } from "./host-contract";
import { inspectImageHeader } from "../projects/images";

export interface EventKioskClientOptions extends EventBrowserOptions { eventId: string; storageOrigin: string }
let activeKioskOperations = 0;
const fail = (code="invalid_response"): never=>{throw new EventClientError(code);};
export async function kioskPhotoApproval(blob: Blob, consent: EventKioskApproval["consent"], missionId: string|null, signal?: AbortSignal): Promise<EventKioskApproval> {
  if(blob.size<1 || blob.size>2000000 || blob.type!=="image/jpeg") return fail("invalid_image");
  const check=()=>{if(signal?.aborted)fail("cancelled");};check();const bytes=new Uint8Array(await blob.arrayBuffer());check();const info=inspectImageHeader(bytes);if(info.mime!=="image/jpeg")return fail("invalid_image");
  const sha256=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(v=>v.toString(16).padStart(2,"0")).join("");check();return parseKioskApproval({...info,bytes:blob.size,sha256,consent,missionId});
}
export function createEventKioskClient(options: EventKioskClientOptions) {
  const app=new URL(options.appOrigin),storage=new URL(options.storageOrigin),eventId=eventClientUuid(options.eventId),fetcher=options.fetch??fetch,life=new AbortController(),timeout=options.timeoutMs??10000;let operations=0;
  if(app.origin!==options.appOrigin || storage.origin!==options.storageOrigin || !["http:","https:"].includes(app.protocol) || storage.protocol!=="https:" && !["localhost","127.0.0.1","[::1]"].includes(storage.hostname) || !Number.isInteger(timeout) || timeout<1 || timeout>10000) return fail("invalid_request");
  const check=(signal?:AbortSignal)=>{if(life.signal.aborted || signal?.aborted)fail("cancelled");};
  const bounded=async(response:Response,max:number,signal:AbortSignal)=>{ const length=response.headers.get("content-length");if(length!==null && (!/^\d+$/.test(length) || Number(length)>max)) {void response.body?.cancel();return fail();}if(!response.body)return fail();const reader=response.body.getReader(), chunks:Uint8Array[]=[];let size=0;try{while(true){check(signal);const next=await reader.read();check(signal);if(next.done)break;size+=next.value.length;if(size>max || chunks.length>=4096)return fail();chunks.push(next.value);}const data=new Uint8Array(size);let offset=0;for(const chunk of chunks){data.set(chunk,offset);offset+=chunk.length;}return data;}finally{void reader.cancel().catch(()=>{});reader.releaseLock();}};
  async function run<T>(signal:AbortSignal|undefined, task:(signal:AbortSignal)=>Promise<T>):Promise<T> {
    check(signal);if(operations>=2||activeKioskOperations>=4)return fail("busy");operations++;activeKioskOperations++;const deadline=new AbortController(),timer=setTimeout(()=>deadline.abort(),timeout),active=AbortSignal.any([life.signal,deadline.signal,...(signal?[signal]:[])]);let interrupted:(()=>void)|undefined;
    const work=task(active).finally(()=>{operations--;activeKioskOperations--;clearTimeout(timer);});
    try{return await Promise.race([work,new Promise<never>((_,reject)=>{interrupted=()=>reject(new EventClientError(life.signal.aborted||signal?.aborted?"cancelled":"unavailable"));active.addEventListener("abort",interrupted,{once:true});if(active.aborted)interrupted();})]);}finally{if(interrupted)active.removeEventListener("abort",interrupted);}
  }
  const request=async(operation:string,body:Record<string,unknown>,signal:AbortSignal,bearer?:string)=>{
    check(signal);const response=await fetcher(`${app.origin}/api/events/${eventId}/kiosk`,{method:"POST",headers:{"content-type":"application/json",...(bearer?{authorization:`Bearer ${bearer}`}:{})},body:JSON.stringify({operation,...body}),credentials:"same-origin",cache:"no-store",redirect:"error",referrerPolicy:"no-referrer",signal});check(signal);
    if(response.redirected || response.headers.get("content-type")?.split(";")[0]!=="application/json") {void response.body?.cancel();return fail();}
    const value:unknown=JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(await bounded(response,32768,signal)));check(signal);
    if(!response.ok){const b=eventClientObject(value,["error"]),code=["access_denied","expired","unavailable","conflict","capacity","not_ready","invalid_request","rate_limited"].includes(String(b.error))?String(b.error):"unavailable";throw new EventClientError(code,response.status);}return value;
  };
  const generation=(v:number)=>{if(!Number.isInteger(v)||v<0||v>10000)return fail("invalid_request");return v;};
  const session=(v:unknown)=>{const s=parseKioskSession(v,eventId);return {...s,expiresAt:eventClientInstant(new Date(s.expiresAt).toISOString())};};
  const grant=(value:unknown,submissionId:string):EventUploadGrant=>{const b=eventClientObject(value,["submissionId","bucket","path","signedUrl","expiresAt","maxBytes","overwrite"]);if(b.submissionId!==submissionId || b.bucket!=="photobooth-event-images-staging-v2" || b.path!==`${eventId}/${submissionId}/source` || b.maxBytes!==2000000 || b.overwrite!==false || typeof b.signedUrl!=="string" || b.signedUrl.length>20000)return fail();const u=new URL(b.signedUrl),expiresAt=eventClientInstant(b.expiresAt);if(u.origin!==storage.origin || u.pathname!==`/storage/v1/object/upload/sign/${b.bucket}/${b.path}` || u.hash || u.username || u.password || [...u.searchParams.keys()].join()!=="token" || !u.searchParams.get("token") || Date.parse(expiresAt)<=Date.now() || Date.parse(expiresAt)>Date.now()+7200000)return fail();return {submissionId,bucket:b.bucket,path:b.path,signedUrl:u.href,expiresAt,maxBytes:2000000,overwrite:false};};
  return {
    eventId,close(){life.abort();},assertActive:check,
    capabilities(signal?:AbortSignal){return run(signal,async active=>{const b=eventClientObject(await request("capabilities",{},active),Object.keys(EVENT_KIOSK_LIMITS));if(Object.entries(EVENT_KIOSK_LIMITS).some(([k,v])=>b[k]!==v))return fail("unavailable");return EVENT_KIOSK_LIMITS;});},
    create(deviceId:string,pin:string,bearer:string,signal?:AbortSignal){return run(signal,async active=>{if(!/^\d{6}$/.test(pin)||!bearer||/\s/.test(bearer))return fail("invalid_request");return session(await request("create",{deviceId:eventClientUuid(deviceId),pin},active,bearer));});},
    session(signal?:AbortSignal){return run(signal,async active=>session(await request("session",{},active)));},
    reset(current:EventKioskSession,requestId:string,signal?:AbortSignal){return run(signal,async active=>{const next=session(await request("reset",{generation:generation(current.generation),requestId:eventClientUuid(requestId)},active));if(next.deviceId!==current.deviceId||next.generation!==current.generation+1)return fail("identity_changed");return next;});},
    begin(current:EventKioskSession,guestId:string,signal?:AbortSignal){return run(signal,async active=>{const next=session(await request("begin",{generation:generation(current.generation),guestId:eventClientUuid(guestId)},active));if(next.deviceId!==current.deviceId||next.generation!==current.generation||next.guestId!==guestId)return fail("identity_changed");return next;});},
    context(current:EventKioskSession,signal?:AbortSignal){return run(signal,async active=>{const b=eventClientObject(await request("context",{generation:generation(current.generation),guestId:eventClientUuid(current.guestId)},active),["version","eventId","title","timezone","startsAt","closesAt","expiresAt","status","look","capacityAvailable","canReserve"]);if(b.version!==1||b.eventId!==eventId||typeof b.title!=="string"||b.title.length>100||typeof b.timezone!=="string"||b.timezone.length>100||!["draft","open","paused","closed","deleted"].includes(String(b.status))||typeof b.capacityAvailable!=="boolean"||typeof b.canReserve!=="boolean")return fail();try{new Intl.DateTimeFormat("en",{timeZone:b.timezone});}catch{return fail();}return {version:1,eventId,title:b.title,timezone:b.timezone,startsAt:eventClientInstant(b.startsAt),closesAt:eventClientInstant(b.closesAt),expiresAt:eventClientInstant(b.expiresAt),status:b.status,look:validateEventLook(b.look),capacityAvailable:b.capacityAvailable,canReserve:b.canReserve} as EventGuestContext;});},
    reserve(current:EventKioskSession,input:{submissionId:string;requestId:string;approval:EventKioskApproval},signal?:AbortSignal){return run(signal,async active=>{const submissionId=eventClientUuid(input.submissionId),b=eventClientObject(await request("reserve",{generation:generation(current.generation),guestId:eventClientUuid(current.guestId),submissionId,requestId:eventClientUuid(input.requestId),approval:parseKioskApproval(input.approval)},active),["submissionId","state","logicalExpiresAt","eventExpiresAt","gallery","wall","deviceId","guestId","generation","stagingPath","stagingHeldBytes","derivativeHeldBytes","receiptToken"]);
      const {deviceId,guestId,generation:gen,stagingPath,stagingHeldBytes,derivativeHeldBytes,receiptToken,...base}=b;if(deviceId!==current.deviceId||guestId!==current.guestId||gen!==current.generation||stagingPath!==`${eventId}/${submissionId}/source`||!Number.isInteger(stagingHeldBytes)||Number(stagingHeldBytes)<0||Number(stagingHeldBytes)>2000000||!Number.isInteger(derivativeHeldBytes)||Number(derivativeHeldBytes)<0||Number(derivativeHeldBytes)>2100000||typeof receiptToken!=="string"||!/^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$/.test(receiptToken))return fail();return {receipt:parseEventReceipt(base,submissionId),receiptToken};});},
    status(gen:number,submissionId:string,signal?:AbortSignal){return run(signal,async active=>parseEventReceipt(await request("status",{generation:generation(gen),submissionId:eventClientUuid(submissionId)},active),submissionId));},
    finalise(gen:number,submissionId:string,signal?:AbortSignal){return run(signal,async active=>parseEventReceipt(await request("finalise",{generation:generation(gen),submissionId:eventClientUuid(submissionId)},active),submissionId));},
    upload(gen:number,submissionId:string,blob:Blob,approval:EventKioskApproval,signal?:AbortSignal){return run(signal,async active=>{
      const actual=await kioskPhotoApproval(blob,approval.consent,approval.missionId,active);check(active);if(JSON.stringify(actual)!==JSON.stringify(parseKioskApproval(approval)))return fail("image_mismatch");
      const signed=grant(await request("upload",{generation:generation(gen),submissionId:eventClientUuid(submissionId)},active),submissionId);check(active);
      const response=await fetcher(signed.signedUrl,{method:"PUT",headers:{"content-type":"image/jpeg","x-upsert":"false"},body:blob,credentials:"omit",cache:"no-store",redirect:"error",referrerPolicy:"no-referrer",signal:active});check(active);void response.body?.cancel();
      if(response.redirected||response.url&&response.url!==signed.signedUrl)return fail("upload_uncertain");if(response.ok)return {acknowledged:true};if(response.status===409)return {acknowledged:false};return fail("upload_uncertain");
    });},
    unlock(pin:string,nonce:string,signal?:AbortSignal){return run(signal,async active=>{if(!/^\d{6}$/.test(pin)||!/^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$/.test(nonce))return fail("invalid_request");return parseKioskUnlock(await request("unlock",{pin,nonce},active));});},
    operator(signal?:AbortSignal){return run(signal,async active=>{const b=eventClientObject(await request("operator",{},active),["deviceId","unlockedUntil"]);return {deviceId:eventClientUuid(b.deviceId),unlockedUntil:eventClientInstant(b.unlockedUntil)};});},
    exit(signal?:AbortSignal){return run(signal,async active=>{const b=eventClientObject(await request("exit",{},active),["deviceId","unlockedUntil"]);return {deviceId:eventClientUuid(b.deviceId),unlockedUntil:eventClientInstant(b.unlockedUntil)};});},
  };
}
export type EventKioskClient = ReturnType<typeof createEventKioskClient>;
