import { eventInstant } from "./event-http-input";
import { createClient } from "@supabase/supabase-js";
import { EVENT_PUBLICATION_LIMITS, parseEventAudienceAccess, parseEventAudiencePage, parseEventAudienceSession, parseEventAudienceValidation, parseEventModerationEntry, parseEventModerationPage, parseEventReportPage, parseEventReportReceipt, publicationDestination, publicationRevision, type EventDestination, type EventReportReason } from "../events/publication-contract";
import { eventClientObject, eventClientUuid } from "../events/client";
import { createEventStore, eventActorId, type EventRpcClient, type VerifiedEventActor } from "./event-store";
import { supabaseServiceOrigin } from "./cron-auth";

function normaliseDates(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Invalid event response");
  const result = { ...value } as Record<string, unknown>;
  for (const key of ["checkedAt","expiresAt","createdAt"]) if (Object.hasOwn(result, key)) result[key] = eventInstant(result[key]);
  if (Array.isArray(result.entries)) result.entries = result.entries.map(normaliseDates);
  return result;
}

export class EventPublicationError extends Error { constructor(readonly code: "unavailable" | "invalid_request" | "access_denied" | "identity_changed" | "conflict" | "capacity" | "expired" | "update_required", readonly status: number) { super(code); } }
const invalid = (): never => { throw new EventPublicationError("invalid_request", 400); };
const bounded = (limit: number) => { if (!Number.isInteger(limit) || limit < 1 || limit > 12) invalid(); return limit; };
export function createEventPublicationStore(env: Record<string, string | undefined> = process.env, provided?: EventRpcClient) {
  const origin = supabaseServiceOrigin(env.NEXT_PUBLIC_SUPABASE_URL), key = env.SUPABASE_SERVICE_ROLE_KEY;
  if (env.PB_EVENTS_ENABLED !== "true" || !origin || !key?.trim()) throw new EventPublicationError("unavailable", 503);
  const client = provided ?? (() => { const admin = createClient(origin, key, { auth: { persistSession: false, autoRefreshToken: false }, global: { fetch: (url, init) => fetch(url, { ...init, signal: init?.signal ? AbortSignal.any([init.signal, AbortSignal.timeout(8000)]) : AbortSignal.timeout(8000) }) } }); return { rpc: async (name: string, args: Record<string, unknown>) => admin.rpc(name, args) }; })();
  const base = createEventStore(env, client);
  const rpc = async (name: string, args: Record<string, unknown> = {}) => {
    const { data, error } = await client.rpc(name, args).catch(() => { throw new EventPublicationError("unavailable", 503); });
    if (error) { const codes: Record<string, [EventPublicationError["code"], number]> = { PB_EVENT_DENIED: ["access_denied", 403], PB_EVENT_IDENTITY_CHANGED: ["identity_changed", 403], PB_EVENT_INVALID: ["invalid_request", 400], PB_EVENT_CONFLICT: ["conflict", 409], PB_EVENT_CAPACITY: ["capacity", 409], PB_EVENT_EXPIRED: ["expired", 410], PB_EVENT_UPDATE_REQUIRED: ["update_required", 503] }; throw new EventPublicationError(...(codes[error.message ?? ""] ?? ["unavailable", 503])); }
    if (data === null || new TextEncoder().encode(JSON.stringify(data)).length > 32768) throw new EventPublicationError("unavailable", 503); return data;
  };
  const parse = <T>(fn: () => T): T => { try { return fn(); } catch { throw new EventPublicationError("unavailable", 503); } };
  const input = <T>(fn: () => T): T => { try { return fn(); } catch { return invalid(); } };
  const capabilities = async () => { const v = await rpc("pb_event_publication_capabilities"); parse(() => { eventClientObject(v, Object.keys(EVENT_PUBLICATION_LIMITS)); if (Object.entries(EVENT_PUBLICATION_LIMITS).some(([k, expected]) => (v as Record<string, unknown>)[k] !== expected)) throw new Error(); }); return EVENT_PUBLICATION_LIMITS; };
  const ready = async () => { await capabilities(); if (!(await base.capabilities()).ready) throw new EventPublicationError("unavailable", 503); };
  const audience = (eventId: string, hash: string, destination: EventDestination, sessionId?: string) => input(() => { if (!/^[a-f0-9]{64}$/.test(hash)) invalid(); return { p_event: eventClientUuid(eventId), p_hash: hash, p_destination: publicationDestination(destination), ...(sessionId === undefined ? {} : { p_session: eventClientUuid(sessionId) }) }; });
  const actor = (subject: VerifiedEventActor, eventId: string) => ({ p_actor: eventActorId(subject), p_event: input(() => eventClientUuid(eventId)) });
  return {
    capabilities,
    async session(eventId: string, hash: string, destination: EventDestination) { const args = audience(eventId, hash, destination); await ready(); const v = await rpc("pb_event_audience_session", args); return parse(() => parseEventAudienceSession(normaliseDates(v), eventId, destination)); },
    async list(eventId: string, hash: string, destination: EventDestination, sessionId: string, after?: string, limit = 12) { const args = audience(eventId, hash, destination, sessionId); bounded(limit); if (after) input(() => eventClientUuid(after)); await ready(); const v = await rpc("pb_event_audience_list", { ...args, p_after: after ?? null, p_limit: limit }); return parse(() => parseEventAudiencePage(normaliseDates(v), eventId, destination, after, limit)); },
    async validate(eventId: string, hash: string, destination: EventDestination, sessionId: string, ids: readonly string[]) { const args = audience(eventId, hash, destination, sessionId); if (!Array.isArray(ids) || ids.length > 12 || new Set(ids).size !== ids.length) invalid(); input(() => ids.forEach(eventClientUuid)); await ready(); const v = await rpc("pb_event_audience_validate", { ...args, p_submissions: ids }); return parse(() => parseEventAudienceValidation(normaliseDates(v), eventId, destination, ids)); },
    async access(eventId: string, hash: string, destination: EventDestination, sessionId: string, submissionId: string, variant: "thumbnail" | "image") { const args = audience(eventId, hash, destination, sessionId); input(() => eventClientUuid(submissionId)); if (!["thumbnail", "image"].includes(variant) || destination === "wall" && variant !== "thumbnail") invalid(); await ready(); const v = await rpc("pb_event_audience_access", { ...args, p_submission: submissionId, p_variant: variant }); return parse(() => parseEventAudienceAccess(normaliseDates(v), eventId, submissionId, variant)); },
    async report(eventId: string, hash: string, destination: EventDestination, sessionId: string, value: { submissionId: string; requestId: string; reason: EventReportReason; detail: string }) { const args = audience(eventId, hash, destination, sessionId); input(() => { eventClientObject(value, ["submissionId", "requestId", "reason", "detail"]); eventClientUuid(value.submissionId); eventClientUuid(value.requestId); }); if (!["privacy", "inappropriate", "other"].includes(value.reason) || typeof value.detail !== "string" || [...value.detail].length > 500 || /[\u0000-\u001f\u007f]/.test(value.detail)) invalid(); await ready(); const v = await rpc("pb_event_audience_report", { ...args, p_submission: value.submissionId, p_request: value.requestId, p_reason: value.reason, p_detail: value.detail }); return parse(() => parseEventReportReceipt(v)); },
    async moderation(subject: VerifiedEventActor, eventId: string, after?: string, limit = 12) { const args = actor(subject, eventId); bounded(limit); if (after) input(() => eventClientUuid(after)); await ready(); const v = await rpc("pb_event_publication_list", { ...args, p_after: after ?? null, p_limit: limit }); return parse(() => parseEventModerationPage(normaliseDates(v), eventId, after, limit)); },
    async decide(subject: VerifiedEventActor, eventId: string, value: { submissionId: string; destination: EventDestination; expectedRevision: number; state: "approved" | "hidden" | "rejected"; requestId?: string }) { const args = actor(subject, eventId); input(() => { eventClientObject(value, ["submissionId", "destination", "expectedRevision", "state"], ["requestId"]); eventClientUuid(value.submissionId); publicationDestination(value.destination); publicationRevision(value.expectedRevision); if (value.requestId) eventClientUuid(value.requestId); }); if (!["approved", "hidden", "rejected"].includes(value.state) || (value.state === "approved") !== (value.requestId !== undefined)) invalid(); await ready(); const v = await rpc("pb_event_publication_decide", { ...args, p_submission: value.submissionId, p_destination: value.destination, p_revision: value.expectedRevision, p_state: value.state, p_request: value.requestId ?? null }); return parse(() => parseEventModerationEntry(normaliseDates(v))); },
    async remove(subject: VerifiedEventActor, eventId: string, submissionId: string, revision: number) { const args = actor(subject, eventId); input(() => { eventClientUuid(submissionId); publicationRevision(revision); }); await ready(); const v = await rpc("pb_event_publication_remove", { ...args, p_submission: submissionId, p_revision: revision }); return parse(() => parseEventModerationEntry(normaliseDates(v))); },
    async hostReport(subject: VerifiedEventActor, eventId: string, value: { submissionId: string; destination: EventDestination; requestId: string; reason: EventReportReason; detail: string }) { const args = actor(subject, eventId); input(() => { eventClientObject(value, ["submissionId", "destination", "requestId", "reason", "detail"]); eventClientUuid(value.submissionId); eventClientUuid(value.requestId); publicationDestination(value.destination); }); if (!["privacy", "inappropriate", "other"].includes(value.reason) || typeof value.detail !== "string" || [...value.detail].length > 500 || /[\u0000-\u001f\u007f]/.test(value.detail)) invalid(); await ready(); const v = await rpc("pb_event_publication_report", { ...args, p_submission: value.submissionId, p_destination: value.destination, p_request: value.requestId, p_reason: value.reason, p_detail: value.detail }); return parse(() => parseEventReportReceipt(v)); },
    async reports(subject: VerifiedEventActor, eventId: string, after?: string, limit = 12) { const args = actor(subject, eventId); bounded(limit); if (after) input(() => eventClientUuid(after)); await ready(); const v = await rpc("pb_event_report_list", { ...args, p_after: after ?? null, p_limit: limit }); return parse(() => parseEventReportPage(normaliseDates(v), eventId, after, limit)); },
    async resolve(subject: VerifiedEventActor, eventId: string, reportId: string) { const args = actor(subject, eventId); input(() => eventClientUuid(reportId)); await ready(); const v = await rpc("pb_event_report_resolve", { ...args, p_report: reportId }); return parse(() => parseEventReportReceipt(v)); },
  };
}
export type EventPublicationStore = ReturnType<typeof createEventPublicationStore>;
