"use client";
import {useEffect,useRef,useState} from 'react';
import {EventKioskShell} from '@/components/events/EventKioskEntry';
import {createEventKioskFixture,type EventKioskFixture} from '@/lib/events/kiosk-ui-fixture';
import {runEventKioskProbe} from '@/lib/events/kiosk-probe';
import {eventControl} from '@/components/events/EventHostControls';
export function EventKioskRehearsal(){
 const [fixture,setFixture]=useState<EventKioskFixture|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[checks,setChecks]=useState<string[]>([]),[generation,setGeneration]=useState(0),[uploadFailure,setUploadFailure]=useState(false);
 const current=useRef<EventKioskFixture|null>(null),alive=useRef(false),running=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;void current.current?.close();current.current=null;};},[]);
 const run=async(task:()=>Promise<void>)=>{if(running.current)return;running.current=true;setBusy(true);setMessage('');try{await task();}catch(error){if(alive.current)setMessage(error instanceof Error?error.message:'Rehearsal failed');}finally{running.current=false;if(alive.current)setBusy(false);}};
 const stop=()=>void run(async()=>{const saved=current.current;current.current=null;setFixture(null);await saved?.close();if(alive.current){setMessage('Stopped. Only this isolated rehearsal database was cleared.');setUploadFailure(false);}});
 return <><aside className="border-b border-border bg-muted px-5 py-6"><div className="mx-auto max-w-5xl"><p className="text-xs font-semibold uppercase tracking-widest">Development rehearsal</p><h1 className="mt-2 font-display text-3xl">Isolated event kiosk</h1><p className="mt-3 max-w-3xl text-sm leading-relaxed">Synthetic camera photo, real client/runtime and isolated IndexedDB. No account, cookies, hosted requests or real event data. The fixture starts already configured; operator PIN is 123456. Production setup/sign-out and real camera permission still require separate checks.</p><div className="mt-4 flex flex-wrap gap-2">
 {!fixture?<button className={`${eventControl} border border-border`} disabled={busy} onClick={()=>void run(async()=>{const next=await createEventKioskFixture({appOrigin:location.origin});if(!alive.current){await next.close();return;}current.current=next;setFixture(next);setMessage('Synthetic device ready. No real browser kiosk lock was set.');})}>Start isolated kiosk</button>:<><button className={`${eventControl} border border-border`} disabled={busy} onClick={stop}>Stop and clear rehearsal</button><button className={eventControl} disabled={busy} onClick={()=>{setGeneration(value=>value+1);setMessage('Guest UI remounted. The server device generation and pending queue are retained.');}}>Remount guest UI</button><button className={eventControl} disabled={busy} onClick={()=>{fixture.loseNextReservation();setMessage('The next reservation will commit but its response will be lost.');}}>Lose next reservation acknowledgement</button><button className={eventControl} disabled={busy} onClick={()=>{const next=!uploadFailure;setUploadFailure(next);fixture.setUploadFailure(next);setMessage(next?'Synthetic Storage uploads now fail.':'Synthetic Storage uploads restored.');}}>{uploadFailure?'Restore uploads':'Fail uploads'}</button><button className={eventControl} disabled={busy} onClick={()=>{fixture.completePending();setMessage('Uploaded pending jobs marked verified ready. Check their receipt or operator queue to reconcile.');}}>Complete pending jobs</button><button className={eventControl} disabled={busy} onClick={()=>{fixture.withdrawPending();setMessage('Pending submissions are withdrawn. Operator export must now refuse them.');}}>Withdraw pending submissions</button><button className={eventControl} disabled={busy} onClick={()=>{fixture.revoke();setMessage('Synthetic device revoked. New work and pending export must fail; PIN-protected exit remains available.');}}>Revoke device</button></>}
 <button className={`${eventControl} border border-border`} disabled={busy||!!fixture} onClick={()=>void run(async()=>{setChecks([]);const result=await runEventKioskProbe();if(alive.current){setChecks(result.checks);setMessage(`${result.passed} native kiosk queue checks passed.`);}})}>Run native kiosk queue checks</button></div>{message&&<p role="status" className="mt-4 text-sm">{message}</p>}{checks.length>0&&<ol className="mt-4 list-decimal space-y-2 pl-5 text-sm">{checks.map(check=><li key={check}>{check}</li>)}</ol>}</div></aside>
 {fixture&&<EventKioskShell key={generation} options={fixture.options} available signedIn={false} accountId={null} accessToken={async()=>null} signOut={async()=>{throw new Error('Fixture never signs out a real account');}} fixturePhoto={fixture.photo} onFixtureExit={stop}/>}</>;
}
