"use client";
import { useRecoveryRelease } from "@/components/ReleaseMode";
import { useAppNavigationGuard } from "@/components/AppNavigation";

import { useEffect, useRef, useState } from "react";
import { cloudControl } from "@/components/cloud/CloudControls";
import type { EventGuestClient } from "@/lib/events/client";
import { validateGuestbookText, type EventGuestbookNote } from "@/lib/events/guestbook-contract";
import { eventGuestError } from "@/lib/events/guest-runtime";

export function EventGuestbookPanel({ client, submissionId, receiptOnly = false, onClose, onInvalid }: { client: EventGuestClient; submissionId: string; receiptOnly?: boolean; onClose(): void; onInvalid(error: unknown): boolean }) {
  const recovery = useRecoveryRelease();
  const [note, setNote] = useState<EventGuestbookNote | null>(null), [message, setMessage] = useState(""), [signature, setSignature] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState<string | null>(null), [pending, setPending] = useState<Parameters<EventGuestClient["saveGuestbook"]>[1] | null>(null), [confirm, setConfirm] = useState<"close" | "withdraw" | "reload" | null>(null);
  const alive = useRef(true), running = useRef(false), work = useRef<AbortController | null>(null), heading = useRef<HTMLHeadingElement>(null), safe = useRef<HTMLButtonElement>(null), invoking = useRef<HTMLElement | null>(null);
  const dirty = !!pending || !!note && (message !== note.message || signature !== note.signature);
  useAppNavigationGuard(() => { if (!busy && !dirty) return true; setNotice(busy ? "Wait for this to finish before you leave." : "Save or close your message before you leave."); return false; });
  const adopt = (next: EventGuestbookNote) => { setNote(next); setMessage(next.message); setSignature(next.signature); requestAnimationFrame(() => { if (alive.current) heading.current?.focus(); }); };
  const run = async (job: (signal: AbortSignal) => Promise<void>) => { if (running.current || !alive.current) return; running.current = true; setBusy(true); setError(null); setNotice(null); const abort = new AbortController(); work.current = abort; try { await job(abort.signal); } catch (e) { if (alive.current && !abort.signal.aborted) { if (onInvalid(e)) return; if (e && typeof e === "object" && "code" in e && e.code === "expired") { setNote(null); setMessage(""); setSignature(""); setPending(null); } const code = e && typeof e === "object" && "code" in e ? e.code : null; setError(code === "capacity" ? "You can't save any more changes, but you can still withdraw your message." : code === "network_error" || code === "timeout" ? "No reply from the server. Try again, or check your saved message." : e instanceof Error && e.message === "invalid_guestbook_text" ? "Keep your message under 500 characters and your name under 80." : eventGuestError(e)); } } finally { running.current = false; if (alive.current) setBusy(false); } };
  const load = () => run(async signal => { const next = await (receiptOnly ? client.receiptGuestbook(submissionId, signal) : client.guestbook(submissionId, signal)); if (!signal.aborted && alive.current) { adopt(next); setPending(null); setConfirm(null); } });
  useEffect(() => { alive.current = true; heading.current?.focus(); const hidden = () => { if (document.hidden) work.current?.abort(); }; document.addEventListener("visibilitychange", hidden); return () => { alive.current = false; work.current?.abort(); document.removeEventListener("visibilitychange", hidden); }; }, []);
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (dirty) { e.preventDefault(); e.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  useEffect(() => { if (confirm) safe.current?.focus(); }, [confirm]);
  const ask = (value: NonNullable<typeof confirm>) => { invoking.current = document.activeElement as HTMLElement; setConfirm(value); };
  const cancel = () => { setConfirm(null); requestAnimationFrame(() => invoking.current?.focus()); };
  const save = () => run(async signal => { if (!note) return; const request = pending ?? { requestId: crypto.randomUUID(), expectedRevision: note.revision, ...validateGuestbookText(message, signature) }; setPending(request); const result = await client.saveGuestbook(submissionId, request, signal); if (!signal.aborted && alive.current) { adopt(result.current); setPending(null); setNotice(result.current.revision === result.acceptedRevision ? "Message saved." : "Saved. A newer version is shown below."); } });
  return <section className="my-7 max-w-2xl border-y border-border py-6" aria-labelledby="guestbook-title"><h2 id="guestbook-title" ref={heading} tabIndex={-1} className="font-display text-3xl outline-none">Guestbook message</h2><p className="mt-3 text-sm leading-relaxed">Only the host, moderators and people with your receipt link can read it. It&apos;s never shown in the gallery or on the wall.</p>
    {error && <p role="alert" className="mt-4">{error}</p>}{notice && <p role="status" className="mt-4">{notice}</p>}
    <div inert={confirm !== null} className="mt-5 space-y-4">
      {!note ? <button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => void load()}>Load message</button> : <>
        {note.mission && <p className="text-sm"><strong>Chosen pose:</strong> {note.mission.label}<span className="mt-1 block">{note.missionCompleted ? "Photo received." : "Waiting for your photo."}</span></p>}
        {note.withdrawn && <p className="text-sm">Your message was withdrawn.</p>}
        {receiptOnly || recovery ? <><p className="whitespace-pre-wrap">{note.message || "No message saved."}</p><p>{note.signature}</p></> : <><label className="block text-sm">Message (optional)<textarea className="mt-2 min-h-32 w-full rounded-xl border border-border bg-background p-3" value={message} disabled={busy || !!pending} onChange={e => setMessage([...e.target.value].slice(0, 500).join(""))} /></label><label className="block text-sm">Your name (optional)<input className="mt-2 min-h-11 w-full rounded-xl border border-border bg-background px-3" value={signature} disabled={busy || !!pending} onChange={e => setSignature([...e.target.value].slice(0, 80).join(""))} /></label><p className="text-sm text-foreground/70">{[...message].length}/500 characters</p><button className={`${cloudControl} bg-accent text-accent-foreground`} disabled={busy || !dirty} onClick={() => void save()}>{pending ? "Try again" : "Save message"}</button></>}
        {pending && <p className="text-sm">This may have already saved. Try again, or check your saved message.</p>}
        <div className="flex flex-wrap gap-2"><button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => dirty ? ask("reload") : void load()}>Check saved message</button><button className={cloudControl} disabled={busy} onClick={() => ask("withdraw")}>Withdraw message</button></div>
      </>}
      <button className={cloudControl} disabled={busy} onClick={() => dirty ? ask("close") : onClose()}>Close</button>
    </div>
    {confirm && <div className="mt-5 rounded-xl bg-muted p-4" role="group" aria-label="Confirm guestbook action"><p className="text-sm leading-relaxed">{confirm === "withdraw" ? "Withdraw your message and name? Your photo isn't affected. Copies already downloaded by the host can't be recalled." : confirm === "reload" ? "Replace your draft with the saved message?" : "Close without saving? Your draft will be lost."}</p><div className="mt-3 flex flex-wrap gap-2"><button ref={safe} className={cloudControl} disabled={busy} onClick={cancel}>Keep editing</button><button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => confirm === "close" ? onClose() : confirm === "reload" ? void load() : void run(async signal => { await client.withdrawGuestbook(submissionId, receiptOnly, signal); if (!signal.aborted && alive.current) { setNote(null); setMessage(""); setSignature(""); setPending(null); setConfirm(null); setNotice("Message withdrawn."); requestAnimationFrame(() => { if (alive.current) heading.current?.focus(); }); } })}>{confirm === "withdraw" ? "Withdraw" : confirm === "reload" ? "Load saved message" : "Discard and close"}</button></div></div>}
  </section>;
}
