/* eslint-disable @next/next/no-img-element -- Preview uses an ephemeral local Blob URL. */
"use client";
import { useAppNavigationGuard } from "@/components/AppNavigation";

import { useCallback, useEffect, useRef, useState } from "react";
import { Camera, Download, ImagePlus, RefreshCw, X } from "lucide-react";
import { cloudControl, cloudSize } from "@/components/cloud/CloudControls";
import { useCamera } from "@/hooks/useCamera";
import { prepareEventGuestPhoto } from "@/lib/events/guest-photo";
import { eventGuestError, invalidateEventGuestSession, type EventGuestSession } from "@/lib/events/guest-runtime";
import { refreshEventGuestRecord, reserveEventGuestRecord, uploadEventGuestRecord, type EventGuestRecord } from "@/lib/events/guest-journal";
import { Dropdown } from "@/components/Dropdown";
import { EVENT_MISSIONS, type EventMissionSettings } from "@/lib/events/guestbook-contract";
import { EventGuestConsentPanel } from "./EventGuestConsentPanel";
import { EventGuestbookPanel } from "./EventGuestbookPanel";
import { downloadProjectBlob } from "@/lib/projects/download";

const when = (value: string) => new Date(value).toLocaleString("en-AU", { dateStyle: "medium", timeStyle: "short" });
export type EventGuestCameraFixture = () => { stream: MediaStream; close(): void };
export function EventGuestWorkspace({ session, onFinish, onInvalid, fixture = false, fixturePhoto, fixtureCamera }: { session: EventGuestSession; onFinish(): Promise<void>; onInvalid(): void; fixture?: boolean; fixturePhoto?(): Promise<Blob>; fixtureCamera?: EventGuestCameraFixture }) {
  const [context, setContext] = useState(session.context), [records, setRecords] = useState<EventGuestRecord[]>([]), [photo, setPhoto] = useState<Blob | null>(null), [preview, setPreview] = useState<string | null>(null), [warning, setWarning] = useState<string | null>(null);
  const [consent, setConsent] = useState({ submission: false, gallery: false, wall: false }), [keep, setKeep] = useState(false), [cameraOn, setCameraOn] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState<string | null>(null), [receiptLink, setReceiptLink] = useState<string | null>(null), [activeId, setActiveId] = useState<string | null>(null), [confirmFinish, setConfirmFinish] = useState(false), [removeId, setRemoveId] = useState<string | null>(null), [withdrawId, setWithdrawId] = useState<string | null>(null), [confirmNext, setConfirmNext] = useState(false), [pendingRequest, setPendingRequest] = useState(false);
  const { videoRef, attachVideo, ready: nativeCameraReady, facing, error: cameraError } = useCamera(cameraOn && !fixture);
  const [missions, setMissions] = useState<EventMissionSettings | null>(null), [missionId, setMissionId] = useState(""), [guestbookId, setGuestbookId] = useState<string | null>(null);
  const [ownConsentAvailable, setOwnConsentAvailable] = useState(false), [consentId, setConsentId] = useState<string | null>(null);
  const guestbookInvoker = useRef<HTMLElement | null>(null);
  const [fixtureReady, setFixtureReady] = useState(false);
  useAppNavigationGuard(() => { if (fixture || !busy && !cameraOn && !photo && !pendingRequest && !receiptLink) return true; setNotice(busy ? "Wait for this photo request to finish before leaving." : "Save your photo and receipt link, then use Finish on this device before leaving."); return false; });
  const cameraReady = fixture ? fixtureReady : nativeCameraReady;
  useEffect(() => {
    if (!fixture || !fixtureCamera || !cameraOn) return;
    let current = true, source: ReturnType<EventGuestCameraFixture> | undefined;
    const video = videoRef.current;
    queueMicrotask(() => {
      if (!current || !video) return;
      setFixtureReady(false);
      try {
        source = fixtureCamera(); video.srcObject = source.stream;
        void video.play().then(() => { if (current) setFixtureReady(true); }, () => { if (current) setError("The synthetic camera preview could not start."); });
      } catch { if (current) setError("The synthetic camera preview is unavailable in this browser."); }
    });
    return () => { current = false; source?.close(); if (video) video.srcObject = null; };
  }, [fixture, fixtureCamera, cameraOn, videoRef]);
  const running = useRef(false), alive = useRef(false), work = useRef<AbortController | null>(null), sourceInput = useRef<HTMLInputElement>(null), retryInput = useRef<HTMLInputElement>(null), retryId = useRef<string | null>(null), request = useRef<{ requestId: string; submissionId: string; missionChoice?: EventGuestRecord["missionChoice"] } | null>(null), heading = useRef<HTMLHeadingElement>(null);
  const invalidate = useCallback((error: unknown) => { if (!invalidateEventGuestSession(error, session)) return false; alive.current = false; work.current?.abort(); request.current = null; retryId.current = null; setCameraOn(false); setPhoto(null); setPreview(null); setReceiptLink(null); setRecords([]); onInvalid(); return true; }, [session, onInvalid]);
  useEffect(() => { alive.current = true; const abort = new AbortController(); work.current = abort; void Promise.all([session.journal.list(), session.client.capabilities(abort.signal).then(cap => { if (!abort.signal.aborted) setOwnConsentAvailable(cap.ownConsentVersion === 1); return cap.guestbookVersion === 1 ? session.client.missions(abort.signal) : null; })]).then(([value, settings]) => { if (!abort.signal.aborted) { setRecords(value); setMissions(settings); } }).catch(e => { if (!abort.signal.aborted && !invalidate(e)) setError(eventGuestError(e)); }); const hidden = () => { if (document.hidden) { work.current?.abort(); setCameraOn(false); } }; document.addEventListener("visibilitychange", hidden); return () => { alive.current = false; abort.abort(); work.current?.abort(); document.removeEventListener("visibilitychange", hidden); }; }, [session, invalidate]);
  useEffect(() => { if (!photo) return; const url = URL.createObjectURL(photo); let current = true; queueMicrotask(() => { if (current) setPreview(url); }); return () => { current = false; URL.revokeObjectURL(url); }; }, [photo]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (photo && !records.some(r => r.submissionId === activeId && (r.blob || r.stage === "ready"))) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [photo, records, activeId]);
  const run = async (job: (signal: AbortSignal) => Promise<void>) => { if (running.current || !alive.current) return; running.current = true; const abort = new AbortController(); work.current = abort; setBusy(true); setError(null); setNotice(null); try { await job(abort.signal); } catch (e) { if (!abort.signal.aborted && alive.current && !invalidate(e)) setError(eventGuestError(e)); } finally { running.current = false; if (alive.current) { setBusy(false); try { const next = await session.journal.list(); if (alive.current) setRecords(next); } catch (error) { if (alive.current) invalidate(error); } } } };
  const choose = (blob: Blob, capturedAt: string | null = null) => run(async signal => { const latest = await session.client.context(signal); const prepared = await prepareEventGuestPhoto(blob, latest, signal, capturedAt); session.client.assertActive(signal); if (!alive.current) return; setContext(latest); setPhoto(prepared.blob); setWarning(prepared.warning); setActiveId(null); setReceiptLink(null); request.current = null; setPendingRequest(false); setCameraOn(false); });
  const capture = () => { const video = videoRef.current; if (!video || !cameraReady || !video.videoWidth) return; void run(async signal => { const canvas = document.createElement("canvas"), scale = Math.min(1, 1600 / Math.max(video.videoWidth, video.videoHeight)); canvas.width = Math.max(1, Math.round(video.videoWidth * scale)); canvas.height = Math.max(1, Math.round(video.videoHeight * scale)); try { const ctx = canvas.getContext("2d"); if (!ctx) throw new Error(); if (facing === "user") { ctx.translate(canvas.width, 0); ctx.scale(-1, 1); } ctx.drawImage(video, 0, 0, canvas.width, canvas.height); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob(b => b ? resolve(b) : reject(new Error()), "image/jpeg", .92)); const latest = await session.client.context(signal), prepared = await prepareEventGuestPhoto(blob, latest, signal, new Date().toISOString()); session.client.assertActive(signal); if (!alive.current) return; setContext(latest); setPhoto(prepared.blob); setWarning(prepared.warning); setActiveId(null); setReceiptLink(null); request.current = null; setPendingRequest(false); setCameraOn(false); } finally { canvas.width = canvas.height = 0; } }); };
  const reserve = () => run(async signal => { if (!photo || !consent.submission) return; const latest = await session.client.context(signal); if (!latest.canReserve && !request.current) { setContext(latest); throw { code: latest.serviceAvailable === false ? "not_ready" : latest.capacityAvailable ? "expired" : "capacity" }; } const ids = request.current ?? { requestId: crypto.randomUUID(), submissionId: crypto.randomUUID(), ...(missions ? { missionChoice: { version: 1 as const, missionId: missionId || null } } : {}) }; request.current = ids; setPendingRequest(true); await session.journal.prepare({ ...ids, consent, blob: photo, keepOnDevice: keep, eventExpiresAt: latest.expiresAt }, signal); const result = await reserveEventGuestRecord(session.journal, session.client, ids.submissionId, signal); session.client.assertActive(signal); if (alive.current) { setActiveId(ids.submissionId); setReceiptLink(`${location.origin}/receipt/${ids.submissionId}?event=${session.client.eventId}#token=${result.receiptToken}`); setNotice("Your private receipt is reserved. Review its expiry, then upload this photo."); requestAnimationFrame(() => heading.current?.focus()); } });
  const upload = (record: EventGuestRecord, blob?: Blob) => run(async signal => { const result = await uploadEventGuestRecord(session.journal, session.client, record.submissionId, blob, signal); if (alive.current) setNotice(result.state === "ready" ? "Your private photo is ready." : "Your upload is awaiting verification. Refresh its status to check again."); });
  const reserveAgain = (record: EventGuestRecord) => run(async signal => { const result = await reserveEventGuestRecord(session.journal, session.client, record.submissionId, signal); if (alive.current) { setActiveId(record.submissionId); setReceiptLink(`${location.origin}/receipt/${record.submissionId}?event=${session.client.eventId}#token=${result.receiptToken}`); setNotice("The same private receipt was recovered. You can now upload its photo."); } });
  return <section className="mt-8" aria-labelledby="event-guest-title">
    <div inert={guestbookId !== null || consentId !== null}><header className="border-b border-border pb-6"><h1 ref={heading} tabIndex={-1} id="event-guest-title" className="font-display text-4xl font-semibold outline-none sm:text-5xl">{context.title}</h1><p className="mt-3 max-w-xl leading-relaxed text-foreground/75">Keep a photo from this gathering. Sharing is your choice.</p><p className="mt-3 text-sm text-foreground/75">Contributions close {when(context.closesAt)}. Event copies expire {when(context.expiresAt)}.</p></header>
    {error && <p role="alert" className="my-5 rounded-xl bg-muted p-4 text-sm leading-relaxed">{error}</p>}{notice && <p role="status" className="my-5 text-sm leading-relaxed">{notice}</p>}
    {!context.canReserve && <p className="mt-5 text-sm leading-relaxed">{context.serviceAvailable === false ? "Photo uploads are temporarily unavailable while the service catches up. Your accepted requests and local copies are preserved." : !context.capacityAvailable ? "This event is currently full." : context.status === "paused" ? "The host has paused new contributions." : "New contributions are not open right now."} Already reserved photos may still finish within their own upload window. Your local download is still available.</p>}
    {!activeId && <div className="grid gap-8 py-7 md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
      <div>{cameraOn ? <video ref={attachVideo} playsInline muted autoPlay className={`aspect-[3/4] w-full rounded-xl bg-muted object-cover ${facing === "user" ? "-scale-x-100" : ""}`} /> : preview && photo ? <img src={preview} alt="Your finished event photo, before upload" className="max-h-[32rem] w-full rounded-xl object-contain" /> : <div className="flex min-h-64 items-center justify-center rounded-xl bg-muted p-8 text-center text-foreground/70"><p>Choose a photo or open your camera.<br />Nothing uploads until you submit.</p></div>}
      <input ref={sourceInput} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={event => { const file = event.currentTarget.files?.[0]; event.currentTarget.value = ""; if (file) void choose(file); }} />
      <div className="mt-4 flex flex-wrap gap-2"><button className={`${cloudControl} border border-border`} disabled={busy || pendingRequest} onClick={() => sourceInput.current?.click()}><ImagePlus size={17} aria-hidden /> {photo ? "Choose another photo" : "Choose a photo"}</button>{fixturePhoto && <button className={`${cloudControl} border border-border`} disabled={busy || pendingRequest} onClick={() => void fixturePhoto().then(blob => choose(blob)).catch(e => { if (alive.current) setError(eventGuestError(e)); })}>Use synthetic photo</button>}{(!fixture || fixtureCamera) && <button className={`${cloudControl} border border-border`} disabled={busy || pendingRequest} onClick={() => { setFixtureReady(false); setCameraOn(value => !value); }}><Camera size={17} aria-hidden /> {cameraOn ? "Close camera" : "Open camera"}</button>}{cameraOn && <button className={`${cloudControl} bg-accent text-accent-foreground`} disabled={busy || !cameraReady} onClick={capture}>Take photo</button>}</div>
      {cameraError && <p role="alert" className="mt-3 text-sm">The camera is unavailable. You can choose a photo instead.</p>}{warning && <p className="mt-3 text-sm leading-relaxed text-foreground/75">{warning}</p>}{photo && <button className={`${cloudControl} mt-3`} disabled={busy} onClick={() => downloadProjectBlob(photo, "my-event-photo.jpg")}><Download size={17} aria-hidden /> Save this finished photo locally</button>}</div>
      <form className="space-y-5" onSubmit={event => { event.preventDefault(); void reserve(); }}><h2 className="font-display text-2xl">Where your photo can appear</h2><p className="text-sm leading-relaxed text-foreground/75">The host and moderators can see your photo, even when public sharing is off.</p>
        {missions && <div><Dropdown label="Optional pose mission" showLabel value={missionId} disabled={busy || pendingRequest} onChange={value => { if (value && Date.now() >= Date.parse(missions.endsAt)) setError("Mission choices have closed. You can still choose no mission while contributions remain open."); else setMissionId(value); }} options={[{ value: "", label: "No mission" }, ...EVENT_MISSIONS.filter(m => missions.missionIds.includes(m.id)).map(m => ({ value: m.id, label: m.label }))]} /><p className="mt-2 text-sm text-foreground/70">Choose a comfortable pose, or skip. Choose by {when(missions.endsAt)}; you cannot change it after reserving.</p></div>}
        {([['submission', 'Submit this photo to the event for private delivery'], ['gallery', 'Also allow this photo in the event gallery'], ['wall', 'Also allow this photo on the public event wall']] as const).map(([key, label]) => <label key={key} className="flex min-h-11 cursor-pointer items-start gap-3 text-sm leading-relaxed"><input type="checkbox" className="mt-1 size-5 shrink-0 accent-accent" checked={consent[key]} disabled={busy || pendingRequest} onChange={event => setConsent(value => ({ ...value, [key]: event.target.checked }))} /><span>{label}</span></label>)}
        <label className="flex min-h-11 cursor-pointer items-start gap-3 text-sm leading-relaxed"><input type="checkbox" className="mt-1 size-5 shrink-0 accent-accent" checked={keep} disabled={busy || pendingRequest} onChange={event => setKeep(event.target.checked)} /><span>Keep this photo temporarily on this device for retry.<span className="mt-1 block text-foreground/70">Optional. It is removed after delivery or within 24 hours (sooner if the event expires). Avoid this on a shared device.</span></span></label>
        <p className="text-sm leading-relaxed text-foreground/75">If you do not keep a device copy, download this finished photo before leaving. Retrying later needs this exact file. Your original stays unchanged.</p>
        <button className={`${cloudControl} bg-accent text-accent-foreground`} disabled={busy || !photo || !consent.submission || !context.canReserve && !pendingRequest}>{busy ? "Preparing…" : pendingRequest ? "Retry the same reservation" : "Get my private receipt"}</button>
      </form>
    </div>}
    {receiptLink && <section className="border-b border-border py-6" aria-label="Your private receipt"><h2 className="font-display text-2xl">Your private receipt</h2><p className="mt-2 text-sm leading-relaxed">Save this link before uploading. Anyone with it can access this private receipt. The event copy is temporary.</p><div className="mt-3 flex flex-wrap gap-2"><button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => void navigator.clipboard.writeText(receiptLink).then(() => setNotice("Private receipt link copied."), () => setError("The browser could not copy the link. Open the private receipt and save it there."))}>Copy private receipt link</button><a href={receiptLink} target="_blank" rel="noopener noreferrer" className={`${cloudControl} border border-border`}>Open private receipt</a></div></section>}
    <section className="py-6" aria-labelledby="event-queue-title"><div className="flex flex-wrap items-center justify-between gap-2"><h2 id="event-queue-title" className="font-display text-2xl">Your pending photos on this device</h2><button className={cloudControl} disabled={busy} onClick={() => void run(async signal => { setContext(await session.client.context(signal)); })}><RefreshCw size={16} aria-hidden /> Check event</button></div><p className="mt-2 text-sm text-foreground/70">This list belongs to your current guest session. It never retries automatically.</p>
    {!records.length && <p className="py-6 text-sm text-foreground/70">No saved requests for this guest yet.</p>}
    <ul className="mt-3">{records.map(record => <li key={record.submissionId} className="border-t border-border py-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-medium">Photo {record.submissionId.slice(0, 8)}</h3><span className="text-sm">{record.receipt?.state === "ready" ? "Ready for private download" : record.receipt?.state === "failed" ? "Verification failed" : record.receipt?.state === "expired" || record.receipt?.state === "deleted" ? "No longer available" : record.stage === "prepared" || record.stage === "reserving" ? "Receipt not confirmed" : record.stage === "reserved" ? "Reserved, photo not uploaded" : record.stage === "uploading" ? "Upload not confirmed" : "Awaiting verification"}</span></div><p className="mt-2 text-sm text-foreground/70">{cloudSize(record.image.bytes)} · {record.blob ? "Photo retained temporarily" : "No original stored in this queue"}. Local request expires {when(record.expiresAt)}.{record.receipt && <> Upload window ends {when(record.receipt.logicalExpiresAt)}.</>}</p>
      <div className="mt-3 flex flex-wrap gap-2">{["prepared", "reserving"].includes(record.stage) ? <button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => void reserveAgain(record)}>Recover private receipt</button> : <><button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => void run(async signal => { const result = await refreshEventGuestRecord(session.journal, session.client, record.submissionId, signal); setNotice(result.state === "ready" ? "Your photo is ready." : `Current delivery status: ${result.state}.`); })}>Refresh status</button>{record.stage !== "ready" && !["failed", "expired", "deleted"].includes(record.receipt?.state ?? "") && <button className={`${cloudControl} bg-accent text-accent-foreground`} disabled={busy} onClick={() => { const source = record.blob ?? (record.submissionId === activeId ? photo : null); if (source || ["uploaded", "finalising"].includes(record.stage)) void upload(record, source ?? undefined); else { retryId.current = record.submissionId; retryInput.current?.click(); } }}>{record.stage === "reserved" ? "Upload this photo" : "Retry this request"}</button>}</>}
      {record.blob && <button className={cloudControl} disabled={busy} onClick={() => downloadProjectBlob(record.blob!, "my-event-photo.jpg")}><Download size={16} aria-hidden /> Save local photo</button>}{record.stage === "ready" && <button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => void run(async signal => { await refreshEventGuestRecord(session.journal, session.client, record.submissionId, signal); const result = await session.client.download(record.submissionId, signal); session.client.assertActive(signal); downloadProjectBlob(result.blob, "my-event-photo.jpg"); })}>Download private photo</button>}
      {ownConsentAvailable && record.receipt && !["deleted", "expired", "failed"].includes(record.receipt.state) && <button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => { guestbookInvoker.current = document.activeElement as HTMLElement; setCameraOn(false); setConsentId(record.submissionId); }}>Photo permissions</button>}
      {missions && record.receipt && !["deleted", "expired", "failed"].includes(record.receipt.state) && <button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => { guestbookInvoker.current = document.activeElement as HTMLElement; setCameraOn(false); setGuestbookId(record.submissionId); }}>Private guestbook and mission</button>}
      <button className={cloudControl} disabled={busy} onClick={() => setRemoveId(record.submissionId)}>Remove local request</button></div>
      {record.receipt && !["deleted", "expired", "failed"].includes(record.receipt.state) && <button className={`${cloudControl} mt-2`} disabled={busy} onClick={() => setWithdrawId(record.submissionId)}>Withdraw event photo</button>}
      {withdrawId === record.submissionId && <div className="mt-3 rounded-xl bg-muted p-4"><p className="text-sm">Withdraw this photo from private event delivery, the gallery and the wall? Existing downloads cannot be recalled. Its local photo stays here until you remove it or the queue expires.</p><div className="mt-2 flex gap-2"><button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => void run(async signal => { const receipt = await session.client.consent(record.submissionId, { submission: false, gallery: false, wall: false }, signal); await session.journal.update(record.submissionId, record.revision, { stage: "failed", receipt }); setWithdrawId(null); setNotice("The event photo was withdrawn. Previously issued media links may take up to five minutes to expire."); })}>Withdraw this event photo</button><button className={cloudControl} disabled={busy} onClick={() => setWithdrawId(null)}>Keep event photo</button></div></div>}
      {removeId === record.submissionId && <div className="mt-3 rounded-xl bg-muted p-4"><p className="text-sm">This removes the local retry record and any retained photo. An unconfirmed request may already be accepted. This does not remove the event submission. Save a local copy first if you need it.</p><div className="mt-2 flex gap-2"><button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => void run(async () => { await session.journal.remove(record.submissionId); setRemoveId(null); if (activeId === record.submissionId || request.current?.submissionId === record.submissionId) { setActiveId(null); setReceiptLink(null); request.current = null; setPendingRequest(false); } })}>Remove this local request</button><button className={cloudControl} onClick={() => setRemoveId(null)}>Keep it</button></div></div>}
    </li>)}</ul><input ref={retryInput} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={event => { const blob = event.currentTarget.files?.[0], record = records.find(r => r.submissionId === retryId.current); event.currentTarget.value = ""; if (blob && record) void upload(record, blob); }} /></section>
    {activeId && <div className="mb-6"><button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => setConfirmNext(true)}>Prepare another photo</button>{confirmNext && <div className="mt-3 max-w-xl"><p className="text-sm leading-relaxed">Save your finished photo and private receipt link before replacing this preview. Any pending request remains in the queue; without device retention, its retry needs that exact finished file.</p><div className="mt-3 flex flex-wrap gap-2">{photo && <button className={cloudControl} onClick={() => downloadProjectBlob(photo, "my-event-photo.jpg")}>Save current photo locally</button>}<button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => { setActiveId(null); setPhoto(null); setPreview(null); setReceiptLink(null); request.current = null; setPendingRequest(false); setConsent({ submission: false, gallery: false, wall: false }); setConfirmNext(false); }}>Continue to another photo</button><button className={cloudControl} disabled={busy} onClick={() => setConfirmNext(false)}>Stay with this photo</button></div></div>}</div>}
    <footer className="border-t border-border py-6"><button className={cloudControl} disabled={busy} onClick={() => setConfirmFinish(true)}><X size={16} aria-hidden /> Finish on this device</button>{confirmFinish && <div className="mt-3 max-w-xl"><p className="text-sm leading-relaxed">Finishing clears this guest&apos;s local requests, retained photos and receipt links from this page. Download any pending photos and copy your private links first. This does not revoke the browser cookie or remove event submissions.</p><div className="mt-3 flex gap-2"><button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => void run(async () => { setCameraOn(false); await onFinish(); })}>Clear local guest data</button><button className={cloudControl} disabled={busy} onClick={() => setConfirmFinish(false)}>Stay here</button></div></div>}</footer>
    </div>{consentId && <EventGuestConsentPanel client={session.client} submissionId={consentId} onInvalid={invalidate} onClose={() => { setConsentId(null); requestAnimationFrame(() => guestbookInvoker.current?.focus()); }} />}{guestbookId && <EventGuestbookPanel client={session.client} submissionId={guestbookId} onInvalid={invalidate} onClose={() => { setGuestbookId(null); requestAnimationFrame(() => guestbookInvoker.current?.focus()); }} />}
  </section>;
}
