"use client";
import { useEffect, useRef, useState } from "react";
import type { EventHostClient } from "@/lib/events/client";
import { EVENT_MISSIONS, type EventMissionSettings } from "@/lib/events/guestbook-contract";
import { prepareEventMissionEdit } from "@/lib/events/mission-edit";
import { eventDateFromLocal, localEventDate } from "@/lib/events/host-actions";
import { EventHostConfirm, eventControl, eventInput, useEventLeaveWarning } from "./EventHostControls";
import { useEventHostTask } from "./useEventHostTask";

export function EventHostGuestbookPanel({ client, eventId, owner, startsAt, closesAt, timezone, disabled = false, onBusyChange, onDirtyChange }: { client: EventHostClient; eventId: string; owner: boolean; startsAt: string; closesAt: string; timezone: string; disabled?: boolean; onBusyChange?(value: boolean): void; onDirtyChange?(value: boolean): void }) {
  const task = useEventHostTask(client), [settings, setSettings] = useState<EventMissionSettings | null>(null), [ids, setIds] = useState<string[]>([]), [end, setEnd] = useState(""), [available, setAvailable] = useState<boolean | null>(null), [page, setPage] = useState<Awaited<ReturnType<EventHostClient["guestbook"]>> | null>(null), [pending, setPending] = useState<ReturnType<typeof prepareEventMissionEdit> | null>(null), [notice, setNotice] = useState<string | null>(null), [confirm, setConfirm] = useState<{ kind: "reload" | "discard"; focus: HTMLElement | null } | null>(null);
  const heading = useRef<HTMLHeadingElement>(null);
  const focusHeading = () => requestAnimationFrame(() => heading.current?.focus());
  const dirty = !!pending || !!settings && (JSON.stringify(ids) !== JSON.stringify(settings.missionIds) || end !== settings.endsAt), blocked = disabled || task.busy || task.lost || !!confirm;
  useEventLeaveWarning(dirty);
  useEffect(() => { onBusyChange?.(task.busy); }, [task.busy, onBusyChange]);
  useEffect(() => { onDirtyChange?.(!task.lost && (dirty || !!confirm)); }, [dirty, confirm, task.lost, onDirtyChange]);
  useEffect(() => () => { onBusyChange?.(false); onDirtyChange?.(false); }, [onBusyChange, onDirtyChange]);
  const adopt = (value: EventMissionSettings) => { setSettings(value); setIds(value.missionIds); setEnd(value.endsAt); };
  const load = () => { if (disabled || task.isBusy()) return; setNotice(null); setPage(null); void task.run(async (signal, check) => { const caps = await client.capabilities(signal); check(); setAvailable(caps.guestbookVersion === 1); if (caps.guestbookVersion !== 1) return; const next = await client.missions(eventId, signal); check(); adopt(next); setPending(null); setConfirm(null); focusHeading(); }); };
  const browse = (after?: string) => { if (blocked || dirty) return; setPage(null); setNotice(null); void task.run(async (signal, check) => { const next = await client.guestbook(eventId, { limit: 25, after }, signal); check(); setPage(next); focusHeading(); }); };
  const save = () => { if (blocked || !settings || !owner) return; setNotice(null); let request = pending; try { request ??= prepareEventMissionEdit(settings, ids, end, { startsAt, closesAt }); } catch { task.setError("Choose up to six listed poses and an end within the contribution window."); return; } const frozen = request; setPending(frozen); void task.run(async (signal, check) => { const next = await client.saveMissions(eventId, frozen, signal); check(); adopt(next); setPending(null); setNotice("Mission settings confirmed. The current saved settings are shown below."); focusHeading(); }); };
  let review = "Enter a valid end time."; try { if (end) review = new Intl.DateTimeFormat("en-AU", { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(end)); } catch {}
  return <section className="border-t border-border py-7"><h3 ref={heading} tabIndex={-1} className="font-display text-2xl outline-none">Pose missions and private guestbook</h3><p className="mt-3 max-w-2xl text-sm leading-relaxed text-foreground/70">Poses are optional. Completion means a photo is ready, not that its pose was checked. Messages stay private.</p>
    {task.error && <p role="alert" className="mt-4 text-sm">{task.error}</p>}{notice && <p role="status" className="mt-4 text-sm">{notice}</p>}
    {task.lost ? <p className="mt-4 text-sm">Private guestbook access changed. Reopen this event to check your account.</p> : <div inert={!!confirm}>
      <button className={`${eventControl} mt-4 border border-border`} disabled={blocked} onClick={() => dirty ? setConfirm({ kind: "reload", focus: document.activeElement as HTMLElement }) : load()}>{settings ? "Check current mission settings" : "Load missions and guestbook access"}</button>
      {dirty && <button className={`${eventControl} mt-4`} disabled={blocked} onClick={() => setConfirm({ kind: "discard", focus: document.activeElement as HTMLElement })}>Discard page mission draft</button>}
      {available === false && <p className="mt-3 text-sm">This event connection does not support private guestbook messages and missions.</p>}
      {settings && available && <><p className="mt-4 text-sm">{settings.locked ? "Mission settings are fixed because a contribution has been accepted." : owner ? "Choose up to six poses before the first contribution is accepted." : "Only the event owner can change mission settings."}</p>
        <fieldset className="mt-4 space-y-3" disabled={blocked || !!pending || settings.locked || !owner}><legend className="sr-only">Optional mission catalogue</legend>{EVENT_MISSIONS.map(mission => <label key={mission.id} className="flex min-h-11 items-start gap-3 text-sm"><input type="checkbox" className="mt-1 size-5 shrink-0 accent-accent" checked={ids.includes(mission.id)} onChange={e => setIds(current => e.target.checked ? [...current, mission.id] : current.filter(id => id !== mission.id))} /><span>{mission.label}</span></label>)}<label className="block text-sm">Mission choices end (device timezone)<input type="datetime-local" className={`${eventInput} mt-2 max-w-sm`} value={localEventDate(end)} onChange={e => { const value = eventDateFromLocal(e.target.value); if (value) setEnd(value); }} /></label></fieldset><p className="mt-3 text-sm">In {timezone}: {review}. Changing missions does not extend the event or photo expiry.</p>
        {owner && <button className={`${eventControl} mt-4 border border-border`} disabled={blocked || !dirty || settings.locked && !pending} onClick={save}>{pending ? "Retry exact mission settings" : "Save mission settings"}</button>}
        {pending && <p className="mt-3 text-sm">These choices may already be saved. Retry or check current settings before reloading.</p>}
        <div className="mt-6 flex flex-wrap gap-2"><button className={`${eventControl} border border-border`} disabled={blocked || dirty} onClick={() => browse()}>Load first private guestbook page</button>{page?.nextCursor && <button className={`${eventControl} border border-border`} disabled={blocked || dirty} onClick={() => browse(page.nextCursor!)}>Next private guestbook page</button>}</div>
        {page && <><p className="mt-3 text-sm text-foreground/70">Refresh to check for withdrawn messages.</p>{!page.entries.length ? <p className="mt-4 text-sm">No guestbook entries on this page.</p> : <ul className="mt-4 divide-y divide-border">{page.entries.map(entry => <li key={entry.submissionId} className="py-4"><p className="break-all font-mono text-xs">{entry.submissionId}</p>{!entry.note ? <p className="mt-2 text-sm">This contribution is no longer available.</p> : <><p className="mt-2 whitespace-pre-wrap text-sm">{entry.note.withdrawn ? "Guestbook text withdrawn." : entry.note.message || "No message supplied."}</p>{entry.note.signature && <p className="mt-2 text-sm">{entry.note.signature}</p>}{entry.note.mission && <p className="mt-2 text-sm text-foreground/70">{entry.note.mission.label} {entry.note.missionCompleted ? "Contribution ready." : "Awaiting verified delivery."}</p>}</>}</li>)}</ul>}</>}
      </>}
    </div>}
    {confirm && <EventHostConfirm title="Replace this page's mission draft?" action={confirm.kind === "discard" ? "Discard local draft" : "Load current settings"} returnFocus={confirm.focus} busy={task.busy} onKeep={() => setConfirm(null)} onConfirm={() => { if (confirm.kind === "reload") load(); else { if (settings) adopt(settings); setPending(null); setConfirm(null); setNotice("The local draft was discarded. This does not undo a saved server action. Check current mission settings before editing again."); } }}><p>Unsaved choices and the local retry request will be replaced. An unconfirmed request may already have reached the event.</p></EventHostConfirm>}
  </section>;
}
