"use client";
import { useAppNavigationGuard } from "@/components/AppNavigation";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Download, RefreshCw } from "lucide-react";
import { cloudControl } from "@/components/cloud/CloudControls";
import { createEventGuestClient, type EventGuestClient } from "@/lib/events/client";
import { eventGuestError, takeEventFragment } from "@/lib/events/guest-runtime";
import type { EventReceipt } from "@/lib/events/contract";
import { downloadProjectBlob } from "@/lib/projects/download";
import { EventGuestbookPanel } from "./EventGuestbookPanel";
import type { EventGuestEntryOptions } from "./EventGuestEntry";

export function EventGuestReceipt({ submissionId, available, options, initialEventId, initialToken }: { submissionId: string; available: boolean; options?: EventGuestEntryOptions; initialEventId?: string; initialToken?: string }) {
  const [receipt, setReceipt] = useState<EventReceipt | null>(null), [error, setError] = useState<string | null>(null), [busy, setBusy] = useState(false), [ready, setReady] = useState(false), [notice, setNotice] = useState<string | null>(null), [eventScope, setEventScope] = useState<string | null>(null), [hasToken, setHasToken] = useState(false);
  const [guestbookClient, setGuestbookClient] = useState<EventGuestClient | null>(null);
  const [guestbookAvailable, setGuestbookAvailable] = useState(false), [guestbookOpen, setGuestbookOpen] = useState(false);
  const guestbookInvoker = useRef<HTMLElement | null>(null);
  const captured = useRef<{ token: string | null; eventId: string | null } | null>(null), client = useRef<EventGuestClient | null>(null), live = useRef(false), controller = useRef<AbortController | null>(null), running = useRef(false);
  useEffect(() => {
    if (!captured.current) captured.current = initialEventId ? { eventId: initialEventId, token: initialToken ?? null } : takeEventFragment("receipt", location, path => history.replaceState(history.state, "", path));
    live.current = true; const abort = new AbortController(); controller.current = abort; const hidden = () => { if (document.hidden) controller.current?.abort(); }; document.addEventListener("visibilitychange", hidden);
    void Promise.resolve().then(async () => { if (abort.signal.aborted) return; setEventScope(captured.current?.eventId ?? null); setHasToken(!!captured.current?.token); if (!available || !captured.current?.eventId) { setError(!available ? "Private event receipts are unavailable here." : "This receipt is missing its event scope. Reopen the complete private receipt link."); return; } const handle = createEventGuestClient({ ...options, appOrigin: options?.appOrigin ?? location.origin, eventId: captured.current.eventId, storageOrigin: options?.storageOrigin ?? process.env.NEXT_PUBLIC_SUPABASE_URL, identity: () => null }); client.current = handle; const caps = await handle.capabilities(abort.signal); if (!abort.signal.aborted) { setReady(true); setGuestbookAvailable(caps.guestbookVersion === 1); } }).catch(e => { if (!abort.signal.aborted) setError(eventGuestError(e)); });
    return () => { document.removeEventListener("visibilitychange", hidden); live.current = false; abort.abort(); controller.current?.abort(); client.current?.close(); client.current = null; };
  }, [available, initialEventId, initialToken, options]);
  const run = async (job: (c: EventGuestClient, signal: AbortSignal) => Promise<void>) => { if (running.current || !client.current) return; running.current = true; setBusy(true); setError(null); setNotice(null); const abort = new AbortController(); controller.current = abort; try { await job(client.current, abort.signal); } catch (e) { if (!abort.signal.aborted && live.current) { setReceipt(null); setError(eventGuestError(e)); } } finally { running.current = false; if (live.current) setBusy(false); } };
  useAppNavigationGuard(() => { if (!busy) return true; setNotice("Wait for this receipt request to finish before leaving."); return false; });
  const open = () => run(async (c, signal) => { const value = captured.current?.token ? await c.exchangeReceipt(submissionId, captured.current.token, signal) : await c.readReceipt(submissionId, signal); if (live.current) setReceipt(value); });
  return <main className="mx-auto min-h-dvh max-w-2xl px-5 py-6 sm:px-8 sm:py-8"><div inert={guestbookOpen}><header className="mt-8"><h1 className="font-display text-4xl font-semibold sm:text-5xl">Your private event photo</h1><p className="mt-4 leading-relaxed text-foreground/75">This private link opens one photo. Share it only with people you trust.</p></header>
    {error && <p role="alert" className="mt-6 rounded-xl bg-muted p-4 text-sm leading-relaxed">{error}</p>}{notice && <p role="status" className="mt-4 text-sm">{notice}</p>}
    {!receipt && <div className="mt-7"><p className="text-sm leading-relaxed">Opening this receipt replaces the previous receipt slot in this browser. Save other private receipt links before continuing.</p><button className={`${cloudControl} mt-4 bg-accent text-accent-foreground`} disabled={!ready || busy} onClick={() => void open()}>{busy ? "Checking…" : "Open this private receipt"}</button></div>}
    {receipt && <section className="mt-7 border-t border-border py-6"><h2 className="font-display text-2xl">{receipt.state === "ready" ? "Ready to keep" : receipt.state === "failed" ? "Photo verification failed" : receipt.state === "expired" ? "This photo has expired" : receipt.state === "deleted" ? "This photo was removed" : receipt.state === "reserved" ? "Reserved, waiting for upload" : receipt.state === "uploading" ? "Upload not confirmed" : "Your photo is being verified"}</h2><p className="mt-3 text-sm leading-relaxed">{receipt.state === "ready" ? "Download a copy before the event storage expires." : ["reserved", "uploading"].includes(receipt.state) ? "Return to the original guest session to retry using the same saved request and photo." : receipt.state === "finalising" ? "Refresh below to check again. This page does not poll or retry automatically." : "An unavailable event copy cannot be recovered through this receipt. Keep any copy you downloaded earlier."}</p><p className="mt-3 text-sm text-foreground/70">Upload window: {new Date(receipt.logicalExpiresAt).toLocaleString("en-AU")}.<br />Event copy expires: {new Date(receipt.eventExpiresAt).toLocaleString("en-AU")}.</p><p className="mt-3 text-sm text-foreground/70">Gallery: {receipt.gallery.replaceAll("_", " ")}. Wall: {receipt.wall.replaceAll("_", " ")}.</p><div className="mt-5 flex flex-wrap gap-2"><button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => void open()}><RefreshCw size={17} aria-hidden /> Refresh status</button>{receipt.state === "ready" && <button className={`${cloudControl} bg-accent text-accent-foreground`} disabled={busy} onClick={() => void run(async (c, signal) => { const result = await c.download(submissionId, signal); c.assertActive(signal); if (live.current) downloadProjectBlob(result.blob, "my-event-photo.jpg"); })}><Download size={17} aria-hidden /> Download photo</button>}{eventScope && <Link href={`/events/${eventScope}/join`} className={cloudControl}>Return to guest session</Link>}</div></section>}
    {guestbookAvailable && receipt && !["deleted", "expired", "failed"].includes(receipt.state) && <button className={`${cloudControl} border border-border`} disabled={busy} onClick={() => { guestbookInvoker.current = document.activeElement as HTMLElement; setGuestbookClient(client.current); setGuestbookOpen(true); }}>View private guestbook and mission</button>}
    {ready && hasToken && <button className={`${cloudControl} mt-4 border border-border`} disabled={busy} onClick={() => { const link = `${location.origin}/receipt/${submissionId}?event=${captured.current!.eventId}#token=${captured.current!.token}`; void navigator.clipboard.writeText(link).then(() => { if (live.current) setNotice("Private receipt link copied."); }, () => { if (live.current) setError("The browser could not copy this link. Keep the original private link you opened."); }); }}>Copy private receipt link</button>}
    <p className="mt-8 text-sm leading-relaxed text-foreground/70">To withdraw the photo, return to the browser session that submitted it. Downloaded copies cannot be recalled.</p>
    </div>{guestbookOpen && guestbookClient && <EventGuestbookPanel client={guestbookClient} submissionId={submissionId} receiptOnly onClose={() => { setGuestbookOpen(false); requestAnimationFrame(() => guestbookInvoker.current?.focus()); }} onInvalid={e => { const code = e && typeof e === "object" && "code" in e ? e.code : null; if (code !== "access_denied" && code !== "identity_changed") return false; setGuestbookOpen(false); setReceipt(null); setError(eventGuestError(e)); return true; }} />}
  </main>;
}
