/* eslint-disable @next/next/no-img-element -- Private thumbnails use one disposable local Blob URL. */
"use client";

import { useEffect, useRef, useState } from "react";
import { RefreshCw, X } from "lucide-react";
import { cloudControl } from "@/components/cloud/CloudControls";
import type { EventReviewClient } from "@/lib/events/review-client";
import type { EventReviewPage } from "@/lib/events/review-contract";

export function EventHostContributionPreview({ client, eventId, disabled = false, onBusyChange }: { client: EventReviewClient; eventId: string; disabled?: boolean; onBusyChange?(busy: boolean): void }) {
  const [page, setPage] = useState<EventReviewPage | null>(null), [preview, setPreview] = useState<{ submissionId: string; url: string } | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [binding, setBinding] = useState({ client, eventId });
  const currentBinding = binding.client === client && binding.eventId === eventId;
  const controller = useRef<AbortController | null>(null), alive = useRef(false), running = useRef(false), url = useRef<string | null>(null), callback = useRef(onBusyChange);
  useEffect(() => { callback.current = onBusyChange; }, [onBusyChange]);
  useEffect(() => { if (!disabled) return; controller.current?.abort(); if (url.current) URL.revokeObjectURL(url.current); url.current = null; let current = true; queueMicrotask(() => { if (current) setPreview(null); }); return () => { current = false; }; }, [disabled]);
  const clear = () => { if (url.current) URL.revokeObjectURL(url.current); url.current = null; setPreview(null); };
  useEffect(() => { alive.current = true; let current = true; queueMicrotask(() => { if (current) { setBinding({ client, eventId }); setPage(null); setPreview(null); setError(null); } }); const hidden = () => { if (document.hidden) { controller.current?.abort(); if (url.current) URL.revokeObjectURL(url.current); url.current = null; setPreview(null); } }; document.addEventListener("visibilitychange", hidden); return () => { current = false; alive.current = false; controller.current?.abort(); if (url.current) URL.revokeObjectURL(url.current); url.current = null; callback.current?.(false); document.removeEventListener("visibilitychange", hidden); }; }, [client, eventId]);
  const run = async (work: (signal: AbortSignal) => Promise<void>) => { if (running.current || disabled) return; running.current = true; const abort = new AbortController(); controller.current = abort; setBusy(true); callback.current?.(true); setError(null); try { await work(abort.signal); } catch (e) { if (alive.current && !abort.signal.aborted) { clear(); const code = e && typeof e === "object" && "code" in e ? e.code : null; if (code === "access_denied" || code === "identity_changed") setPage(null); setError(code === "access_denied" || code === "identity_changed" ? "Private review access changed. Refresh your event access before continuing." : "Private previews are unavailable. Check the connection and that this server supports private review, then try again."); } } finally { running.current = false; if (alive.current) setBusy(false); callback.current?.(false); } };
  const load = (after?: string) => run(async signal => { clear(); await client.capabilities(eventId, signal); const result = await client.list(eventId, after, 12, signal); client.assertActive(signal); if (alive.current) setPage(result); });
  useEffect(() => {
    if (!preview || !currentBinding || disabled) return; const abort = new AbortController();
    const timer = setInterval(() => { if (running.current || document.hidden) return; running.current = true; void client.access(eventId, preview.submissionId, abort.signal).catch(error => { if (!abort.signal.aborted && alive.current) { if (url.current) URL.revokeObjectURL(url.current); url.current = null; setPreview(null); const code = error && typeof error === "object" && "code" in error ? error.code : null; if (code === "access_denied" || code === "identity_changed") setPage(null); setError("This private preview could not be reauthorised and has been cleared. Refresh contributions before reopening it."); } }).finally(() => { running.current = false; }); }, 10000);
    return () => { clearInterval(timer); abort.abort(); };
  }, [client, eventId, preview, currentBinding, disabled]);
  return <section className="border-t border-border py-6" aria-labelledby="event-private-review-title"><h2 id="event-private-review-title" className="font-display text-2xl">Private contribution review</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-foreground/75">For the owner and moderators only. Withdrawn photos cannot be opened.</p>
    <div className="mt-4 flex flex-wrap gap-2"><button className={`${cloudControl} border border-border`} disabled={disabled || busy} onClick={() => void load()}><RefreshCw size={17} aria-hidden /> {busy ? "Checking…" : page ? "Refresh contributions" : "Load contributions"}</button>{busy && <button className={cloudControl} onClick={() => { controller.current?.abort(); clear(); }}>Cancel preview request</button>}</div>
    {error && <p role="alert" className="mt-3 text-sm leading-relaxed">{error}</p>}{busy && <p role="status" className="mt-3 text-sm">Checking current private access…</p>}
    {currentBinding && !disabled && preview && <figure className="mt-5"><img src={preview.url} alt="Private event contribution thumbnail" className="max-h-80 max-w-full rounded-xl object-contain" /><figcaption className="mt-2 text-sm text-foreground/70">Private preview, not a public gallery.</figcaption><button className={cloudControl} onClick={clear}><X size={17} aria-hidden /> Close thumbnail</button></figure>}
    {currentBinding && page && <><ul className="mt-4">{page.entries.map(entry => <li key={entry.submissionId} className="flex flex-wrap items-center justify-between gap-3 border-t border-border py-3"><div><p className="font-medium">Photo {entry.submissionId.slice(0, 8)}</p><p className="mt-1 text-sm text-foreground/70">{new Date(entry.createdAt).toLocaleString("en-AU")} · {entry.state}</p></div><button className={`${cloudControl} border border-border`} disabled={disabled || busy || !entry.thumbnailAvailable} onClick={() => void run(async signal => { clear(); const blob = await client.download(eventId, entry.submissionId, signal); client.assertActive(signal); if (!alive.current) return; const next = URL.createObjectURL(blob); url.current = next; setPreview({ submissionId: entry.submissionId, url: next }); })}>{entry.thumbnailAvailable ? "Open thumbnail" : "Preview unavailable"}</button></li>)}</ul>{!page.entries.length && <p className="mt-4 text-sm text-foreground/70">No contributions on this page.</p>}{page.nextCursor && <button className={`${cloudControl} mt-3 border border-border`} disabled={disabled || busy} onClick={() => void load(page.nextCursor!)}>Next contributions</button>}</>}
  </section>;
}
