"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { EventAudienceEntry } from "@/components/events/EventAudienceEntry";
import { Dropdown } from "@/components/Dropdown";
import { eventControl } from "@/components/events/EventHostControls";
import { createEventAudienceFixture, type EventAudienceFixture } from "@/lib/events/audience-fixture";
import { runEventAudienceProbe } from "@/lib/events/audience-probe";

export function EventAudienceRehearsal() {
  const [fixture, setFixture] = useState<EventAudienceFixture | null>(null), [destination, setDestination] = useState<"gallery" | "wall">("gallery"), [version, setVersion] = useState(0), [busy, setBusy] = useState(false), [message, setMessage] = useState("No synthetic session is running."), [checks, setChecks] = useState<string[]>([]);
  const [dark, setDark] = useState(true);
  const owned = useRef<EventAudienceFixture | null>(null), alive = useRef(false), active = useRef(false);
  useEffect(() => { alive.current = true; return () => { alive.current = false; owned.current?.close(); }; }, []);
  const options = useMemo(() => fixture ? { appOrigin: location.origin, storageOrigin: location.origin, initialToken: fixture.tokens[destination], fetch: fixture.fetch } : undefined, [fixture, destination]);
  const start = async () => { if (active.current || owned.current) return; active.current = true; setBusy(true); try { const next = await createEventAudienceFixture({ appOrigin: location.origin }); if (!alive.current) { next.close(); return; } owned.current = next; setFixture(next); setMessage("Synthetic audience ready. No account or provider is used."); } catch { if (alive.current) setMessage("The local JPEG fixture could not start."); } finally { active.current = false; if (alive.current) setBusy(false); } };
  const stop = () => { owned.current?.close(); owned.current = null; setFixture(null); setMessage("Synthetic sessions and photos cleared."); };
  const probe = async () => { if (active.current || fixture) return; active.current = true; setBusy(true); setChecks([]); try { const result = await runEventAudienceProbe(); if (alive.current) { setChecks(result.checks); setMessage(`${result.checks.length} native checks passed at ${result.checkedAt}.`); } } catch (error) { if (alive.current) setMessage(error instanceof Error ? error.message : "Native check failed"); } finally { active.current = false; if (alive.current) setBusy(false); } };
  return <div className={`${dark ? "dark" : "light"} min-h-dvh bg-background text-foreground`}><section className="mx-auto max-w-6xl border-b border-border px-5 py-7"><h1 className="font-display text-3xl">Audience rehearsal</h1><p className="mt-3 max-w-3xl text-sm leading-relaxed">Development only. Real gallery/wall clients and components use a local JPEG and synthetic authority. The rows include neither destination, gallery only, wall only and both. No real account, event or provider is accessed.</p><div className="mt-5 flex flex-wrap gap-2"><button className={`${eventControl} border border-border`} onClick={() => setDark(value => !value)}>{dark ? "Inspect light theme" : "Inspect dark theme"}</button><button className={`${eventControl} border border-border`} disabled={busy || Boolean(fixture)} onClick={() => void start()}>Start synthetic audience</button><button className={eventControl} disabled={!fixture} onClick={stop}>Stop and clear</button><button className={`${eventControl} border border-border`} disabled={busy || Boolean(fixture)} onClick={() => void probe()}>Run native audience checks</button></div><p role="status" className="mt-4 text-sm">{busy ? "Working locally…" : message}</p>{checks.length > 0 && <ul className="mt-3 list-disc pl-5 text-sm">{checks.map(check => <li key={check}>{check}</li>)}</ul>}
    {fixture && <><div className="mt-5 max-w-xs"><Dropdown label="Audience destination" showLabel value={destination} options={[{ value: "gallery", label: "Gallery" }, { value: "wall", label: "Wall" }]} onChange={value => { setDestination(value as "gallery" | "wall"); setVersion(x => x + 1); }} /></div><div className="mt-4 flex flex-wrap gap-2"><button className={eventControl} onClick={() => { fixture.withdrawGallery(true); setMessage("Gallery grants withdrawn. The next check must hide gallery photos; wall grants stay unchanged."); }}>Withdraw gallery grants</button><button className={eventControl} onClick={() => { fixture.hideFirstWall(true); setMessage("First wall photo hidden. Watch the next permission check."); }}>Hide first wall photo</button><button className={eventControl} onClick={() => { fixture.failChecks(true); setMessage("Permission requests now fail. Photos must clear, never remain as an offline cache."); }}>Fail permission checks</button><button className={eventControl} onClick={() => { fixture.replaceSession(destination); setMessage("This destination's cookie was replaced. The old client must reject its next request."); }}>Replace viewing session</button><button className={eventControl} onClick={() => { fixture.expire(true); setMessage("Synthetic event expired. All audience reads must stop."); }}>Expire event</button><button className={eventControl} onClick={() => { fixture.expire(false); fixture.revoke(false); fixture.failChecks(false); fixture.withdrawGallery(false); fixture.hideFirstWall(false); setMessage("Synthetic authority restored. Check again or reopen the view."); }}>Restore approvals</button><button className={eventControl} onClick={() => setVersion(x => x + 1)}>Remount audience page</button></div></>}
  </section>{fixture && <EventAudienceEntry key={`${destination}:${version}`} eventId={fixture.eventId} destination={destination} available options={options} />}</div>;
}
