"use client";
import { useEffect, useRef, useState } from "react";
import { EventPostcardComposer } from "@/components/events/EventPostcardComposer";
import { eventControl } from "@/components/events/EventHostControls";
import { createPostcardUIFixture } from "@/lib/events/postcard-ui-fixture";
import { runPostcardPhotoProbe } from "@/lib/events/postcard-photo-probe";
import { runPostcardJournalProbe } from "@/lib/events/postcard-journal-probe";

type Fixture = ReturnType<typeof createPostcardUIFixture>;
export default function PostcardRehearsal() {
  const [fixture, setFixture] = useState<Fixture | null>(null), [mount, setMount] = useState<ReturnType<Fixture["mount"]> | null>(null), [serial, setSerial] = useState(0), [role, setRole] = useState(0), [dark, setDark] = useState(false), [busy, setBusy] = useState(false), [report, setReport] = useState("");
  const [initialId, setInitialId] = useState<string | undefined>();
  const owned = useRef<Fixture | null>(null);
  useEffect(() => () => owned.current?.close(), []);
  const start = () => { const next = createPostcardUIFixture(location.origin); owned.current = next; setFixture(next); setInitialId(undefined); setMount(next.mount()); setRole(0); setSerial(v => v + 1); setReport("Started isolated synthetic event. Connect, then start a postcard as role A."); };
  const remount = (nextRole = role) => { if (!fixture) return; fixture.switchRole(nextRole); setInitialId(fixture.latestId()); setRole(nextRole); setMount(fixture.mount()); setSerial(v => v + 1); setReport("Previous source and guest runtime closed. Connect again to recover or join the existing postcard."); };
  const stop = async () => { if (!fixture) return; setFixture(null); setMount(null); fixture.close(); owned.current = null; await new Promise(resolve => setTimeout(resolve, 0)); try { for (const name of [fixture.databaseName, `${fixture.databaseName}-guest`]) await new Promise<void>((resolve, reject) => { const request = indexedDB.deleteDatabase(name); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error); request.onblocked = () => reject(new Error("Cleanup blocked. Close this rehearsal in other tabs.")); }); setReport("Stopped. Synthetic server state and both unique local databases cleared."); } catch (error) { setReport(String(error)); } };
  const probe = async (kind: "photo" | "journal") => { if (!fixture) return; setBusy(true); try { const result = kind === "photo" ? await runPostcardPhotoProbe() : await runPostcardJournalProbe({ postcardId: crypto.randomUUID(), submissionId: crypto.randomUUID(), source: fixture.source, design: fixture.design }); setReport(result.checks.map(c => `${c.passed ? "PASS" : "FAIL"}: ${c.name}`).join("\n")); } catch (error) { setReport(String(error)); } finally { setBusy(false); } };
  return <main data-theme={dark ? "dark" : "light"} className={`${dark ? "dark" : ""} min-h-screen bg-background px-5 py-10 text-foreground`}><div className="mx-auto max-w-4xl">
    <h1 className="font-display text-4xl">Synthetic remote postcards</h1><p className="mt-4 text-sm leading-relaxed">Development rehearsal only. Two fake source principals and two separate fake event guests, no accounts, provider requests or hosted changes. The real composer, JPEG encoder and browser journals run here.</p>
    <div className="my-5 flex flex-wrap gap-2"><button className={`${eventControl} border border-border`} onClick={() => setDark(v => !v)}>Use {dark ? "light" : "dark"} theme</button>{!fixture ? <button className={`${eventControl} bg-accent text-accent-foreground`} onClick={start}>Start isolated rehearsal</button> : <><button className={eventControl} disabled={busy} onClick={() => remount(role === 0 ? 1 : 0)}>Switch to role {role === 0 ? "B" : "A"}</button><button className={eventControl} disabled={busy} onClick={() => remount()}>Remount current role</button><button className={eventControl} disabled={busy} onClick={() => void stop()}>Stop and clear rehearsal</button></>}</div>
    {fixture && <><p className="font-semibold">Current contributor: role {role === 0 ? "A" : "B"}</p><p className="mt-2 text-sm leading-relaxed">1. Connect and start as A, save submission permission. 2. Switch to B, connect to join the existing postcard and save permission. 3. Return to A, refresh, prepare the full strip and send it. 4. Release verification, then each role reviews and approves the exact JPEG. Public permissions begin off.</p><div className="my-5 flex flex-wrap gap-2">
      <button className={eventControl} disabled={busy} onClick={() => { fixture.loseTicket(); setReport("Next ticket acknowledgement will be lost after acceptance."); }}>Lose next ticket response</button><button className={eventControl} disabled={busy} onClick={() => { fixture.loseReservation(); setReport("Next reservation acknowledgement will be lost after acceptance."); }}>Lose next reservation response</button><button className={eventControl} disabled={busy} onClick={() => { fixture.losePermissions(); setReport("Next permission acknowledgement will be lost after acceptance."); }}>Lose next permission response</button><button className={eventControl} disabled={busy} onClick={() => void fixture.release().then(() => setReport("Synthetic worker released. Refresh postcard status."))}>Release verification</button><button className={eventControl} disabled={busy} onClick={() => { fixture.withdraw(); setReport("Another contributor withdrew. Refresh or wait for preview recheck."); }}>Withdraw externally</button><button className={eventControl} disabled={busy} onClick={() => setReport(JSON.stringify(fixture.summary(), null, 2))}>Inspect synthetic status</button><button className={eventControl} disabled={busy} onClick={() => void probe("photo")}>Run native strip checks</button><button className={eventControl} disabled={busy} onClick={() => void probe("journal")}>Run native journal checks</button>
    </div></>}
    {report && <pre role="status" className="my-5 whitespace-pre-wrap rounded-xl bg-muted p-4 text-sm">{report}</pre>}
    {fixture && mount && <EventPostcardComposer key={serial} source={fixture.source} design={fixture.design} initialEventId={fixture.eventId} initialPostcardId={initialId} options={fixture.options} assertSourceActive={mount.assertActive} sourceAccessToken={mount.accessToken} render={fixture.render} onBusyChange={setBusy} />}
  </div></main>;
}
