"use client";
import { useEffect, useRef, useState } from "react";
import LegacyRoom from "@/components/rooms/LegacyRoom";
import { createLegacyRoomFixture, type LegacyRoomFixture } from "@/lib/rtc/legacy-room-fixture";

export default function LegacyRoomRehearsal() {
  const [fixture, setFixture] = useState<LegacyRoomFixture | null>(null), [selected, setSelected] = useState(0), [guestPresent, setGuestPresent] = useState(true), [busy, setBusy] = useState(false), [status, setStatus] = useState("Not started."), [diagnostics, setDiagnostics] = useState<string[]>([]), [light, setLight] = useState(false);
  const current = useRef<LegacyRoomFixture | null>(null), generation = useRef(0);
  useEffect(() => () => { generation.current++; void current.current?.stop().catch(() => {}); }, []);
  useEffect(() => { if (!fixture) return; const timer = setInterval(() => setDiagnostics([...fixture.diagnostics]), 500); return () => clearInterval(timer); }, [fixture]);
  const start = async () => { setBusy(true); const expected = generation.current; try { const next = await createLegacyRoomFixture(); if (generation.current !== expected) { await next.stop(); return; } current.current = next; setFixture(next); setGuestPresent(true); setSelected(0); setStatus("Both actual legacy rooms are mounted with local streams and separate databases."); } catch (error) { setStatus(String(error)); } finally { setBusy(false); } };
  const stop = async () => { const previous = current.current; if (!previous) return; generation.current++; setBusy(true); setFixture(null); current.current = null; try { await previous.stop(); setDiagnostics([...previous.diagnostics]); setStatus("Stopped: both streams, engines and isolated databases cleared."); } catch (error) { setStatus(String(error)); } finally { setBusy(false); } };
  const inspect = async () => { if (!fixture) return; setBusy(true); try { await fixture.inspect(); setDiagnostics([...fixture.diagnostics]); setStatus("Saved originals reopened and checked."); } catch (error) { setStatus(String(error)); } finally { setBusy(false); } };
  const button = "min-h-11 rounded-xl border border-border bg-card px-4 text-sm disabled:opacity-50";
  return <div className={`${light ? "light" : "dark"} min-h-dvh bg-background text-foreground`}><section className="space-y-3 border-b border-border p-5"><h1 className="font-display text-2xl">Synthetic legacy room rehearsal</h1><p className="max-w-3xl text-sm">Actual legacy room controls and peer engine. Local BroadcastChannel and peer connections with no ICE servers, synthetic canvas streams, separate temporary databases. No camera, microphone or hosted signalling. Keep Scene set to None.</p><div className="flex flex-wrap gap-3"><button className={button} onClick={() => setLight(value => !value)}>Inspect {light ? "dark" : "light"} theme</button>{fixture ? <><button className={button} disabled={busy} onClick={() => void stop()}>Stop and clear</button><button className={button} disabled={busy} onClick={() => fixture.failNextHostSave()}>Refuse next host original save</button><button className={button} disabled={busy} onClick={() => void inspect()}>Reopen saved originals</button><button className={button} disabled={busy || !guestPresent} onClick={() => { setGuestPresent(false); setSelected(0); void fixture.disconnectGuest().catch(error => setStatus(String(error))); }}>Disconnect guest</button></> : <button className={button} disabled={busy} onClick={() => void start()}>Start two legacy peers</button>}</div><p role="status">{status}</p>{fixture && <nav aria-label="Synthetic legacy participant" className="flex gap-3"><button className={button} aria-pressed={selected === 0} onClick={() => setSelected(0)}>Host</button><button className={button} disabled={!guestPresent} aria-pressed={selected === 1} onClick={() => setSelected(1)}>Guest</button></nav>}<pre className="max-h-44 overflow-auto whitespace-pre-wrap text-xs">{diagnostics.join("\n")}</pre></section>{fixture?.people.map((person, index) => index === 0 || guestPresent ? <div key={person.name} hidden={selected !== index}><LegacyRoom rehearsal={person.props} /></div> : null)}</div>;
}
