"use client";
import Link from "next/link";
import { runEventExportProbe } from "@/lib/events/export-probe";
import { useEffect, useRef, useState } from "react";
import { createEventHostUIFixture } from "@/lib/events/host-ui-fixture";
import type { EventHostClient } from "@/lib/events/client";
import { EventHostWorkspace } from "@/components/events/EventHostWorkspace";
import { eventControl } from "@/components/events/EventHostControls";

export default function EventHostRehearsal() {
  const [fixture, setFixture] = useState<ReturnType<typeof createEventHostUIFixture> | null>(null), [client, setClient] = useState<EventHostClient | null>(null), [person, setPerson] = useState(0), [version, setVersion] = useState(0), [notice, setNotice] = useState<string | null>(null), [dark, setDark] = useState(true);
  const [probe, setProbe] = useState<Awaited<ReturnType<typeof runEventExportProbe>> | null>(null), [probing, setProbing] = useState(false);
  const active = useRef<typeof fixture>(null);
  useEffect(() => () => active.current?.close(), []);
  const mount = (index: number) => { if (fixture) { setClient(fixture.mount(index)); setPerson(index); setVersion(value => value + 1); } };
  return <main className={`${dark ? "dark" : "light"} min-h-dvh bg-background px-5 py-6 text-foreground`}><div className="mx-auto max-w-6xl">
    <Link href="/v2-lab" className="text-sm underline">Back to development lab</Link><h1 className="mt-6 font-display text-4xl">Event host rehearsal</h1><p className="mt-3 max-w-3xl text-sm leading-relaxed text-foreground/70">Real host screens and client, temporary in-memory server. No real accounts, hosted writes or guest invitations. Refresh resets this simulated server. Pending requests exist only in the mounted page; remount demonstrates their loss and discovery recovery.</p>
    <button className={`${eventControl} mt-4 border border-border`} disabled={probing} onClick={() => { setProbing(true); void runEventExportProbe().then(setProbe).finally(() => setProbing(false)); }}>Run isolated export checks</button>{probing && <p role="status">Running isolated export checks…</p>}{probe && <section aria-label="Export check results"><p role="status">{probe.passed ? "All export checks passed" : "Export checks need attention"}</p><ul>{probe.checks.map(check => <li key={check.name}>{check.passed ? "PASS" : "FAIL"}: {check.name}{check.detail ? `: ${check.detail}` : ""}</li>)}</ul></section>}
    <div className="my-5 flex flex-wrap gap-2"><button className={`${eventControl} border border-border`} onClick={() => setDark(value => !value)}>{dark ? "Inspect light theme" : "Inspect dark theme"}</button>{!fixture ? <button className={`${eventControl} bg-accent text-accent-foreground`} onClick={() => { const next = createEventHostUIFixture(location.origin); active.current = next; setFixture(next); setClient(next.mount(0)); setPerson(0); }}>Start host rehearsal</button> : <>
      <button className={`${eventControl} border border-border`} onClick={() => { fixture.close(); active.current = null; setFixture(null); setClient(null); setNotice(null); }}>Stop and clear rehearsal</button>
      {fixture.people.filter((_, index) => index !== person).map(candidate => <button key={candidate.id} className={`${eventControl} border border-border`} onClick={() => mount(fixture.people.findIndex(item => item.id === candidate.id))}>Switch to {candidate.name}</button>)}
      <button className={`${eventControl} border border-border`} onClick={() => mount(person)}>Remount same account</button><button className={`${eventControl} border border-border`} onClick={() => { fixture.loseNextAcknowledgement(); setNotice("The next successful mutation commits, then loses its response. Retry its exact request in the workspace."); }}>Lose next mutation response</button>
      <button className={`${eventControl} border border-border`} onClick={() => { fixture.seedGuestbook(); setNotice("Twenty-six private notes seeded. Mission settings are now locked. Load the first guestbook page."); }}>Add private guestbook pages</button><button className={`${eventControl} border border-border`} onClick={() => { fixture.withdrawGuestbook(); setNotice("The first private note was withdrawn. Reload its page to verify the text is gone."); }}>Withdraw first private note</button>
      <button className={`${eventControl} border border-border`} onClick={() => { fixture.editElsewhere(); setNotice("The seeded event settings advanced elsewhere. Existing settings edits should conflict."); }}>Advance seeded settings</button><button className={`${eventControl} border border-border`} onClick={() => { fixture.acceptContribution(); setNotice("The seeded event has an accepted contribution and a failed delivery. Refresh to inspect its locked look and held storage."); }}>Accept synthetic contribution</button>
      <button className={`${eventControl} border border-border`} onClick={() => { const current = fixture; void current.seedReadyContribution().then(() => { if (active.current === current) setNotice("A local synthetic ready JPEG is available. Load private contributions, then open its thumbnail explicitly."); }).catch(() => { if (active.current === current) setNotice("Synthetic photo generation failed. Try again."); }); }}>Add ready private photo</button><button className={`${eventControl} border border-border`} onClick={() => { fixture.withdrawReadyContribution(); setNotice("The ready photo was withdrawn. Open previews should clear on their next authority check; fresh thumbnail reads are denied."); }}>Withdraw ready private photo</button>
      <button className={`${eventControl} border border-border`} onClick={() => { fixture.reminderTargets(false); setNotice("Synthetic account has no verified email or push subscriptions. Refresh reminder status to inspect actual availability."); }}>Remove reminder targets</button><button className={`${eventControl} border border-border`} onClick={() => { fixture.reminderTargets(true); setNotice("Synthetic verified email and push subscriptions restored. No real delivery occurs."); }}>Restore reminder targets</button>
      <button className={`${eventControl} border border-border`} onClick={() => { const current = fixture; void current.seedPublicationChoices().then(() => { if (active.current === current) setNotice("Four ready photos now cover private, gallery only, wall only and both consents. Load publication review; no photo is approved yet."); }).catch(() => { if (active.current === current) setNotice("Synthetic photo generation failed. Try again."); }); }}>Add four publication choices</button>
      <button className={`${eventControl} border border-border`} onClick={() => { fixture.changePublicationConsent(false); setNotice("Both-consent photo lost gallery consent. An old approval revision must now conflict; wall consent is unchanged."); }}>Withdraw gallery consent</button>
      <button className={`${eventControl} border border-border`} onClick={() => { fixture.changePublicationConsent(true); setNotice("Gallery consent was renewed. Fresh approval is required; an old request cannot approve it again."); }}>Renew gallery consent</button>
      <button className={`${eventControl} border border-border`} onClick={() => { fixture.expireSeededEvent(); setNotice("The seeded event has expired. Fresh publication and private-media operations must deny access."); }}>Expire seeded event</button>
      <button className={`${eventControl} border border-border`} onClick={() => { fixture.oldServer(true); mount(person); }}>Simulate old host server</button><button className={`${eventControl} border border-border`} onClick={() => { fixture.oldServer(false); mount(person); }}>Restore host support</button><button className={`${eventControl} border border-border`} onClick={() => { fixture.revokeAccess(); setClient(null); setNotice("Synthetic account access revoked. Its workspace and invitation are gone."); }}>Revoke account access</button>
    </>}</div>{notice && <p role="status" className="mb-5 text-sm">{notice}</p>}{fixture && <p className="mb-5 text-sm">Synthetic account: {fixture.people[person].name} ({fixture.people[person].id})</p>}{client && <EventHostWorkspace key={`${person}:${version}`} client={client} reminderClient={fixture?.reminderClient} reviewClient={fixture?.reviewClient} moderationClient={fixture?.moderationClient} />}
  </div></main>;
}
